# Generated by Django 5.2.13 on 2026-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popia', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dsarrequest',
            new_name='popia_dsarr_status_44a393_idx',
            old_name='popia_dsar_status_sla_idx',
        ),
        migrations.RenameIndex(
            model_name='dsarrequest',
            new_name='popia_dsarr_request_f1fe38_idx',
            old_name='popia_dsar_requester_type_idx',
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('consumed', 'Consumed (downloaded)')], default='queued', max_length=20),
        ),
    ]
