# Generated by Django 5.2.12 on 2026-03-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_created_651c44_idx',
            old_name='notificatio_created_e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_channel_f70f70_idx',
            old_name='notificatio_channel_0f2_idx',
        ),
    ]
