# Generated by Django 5.2.12 on 2026-04-23 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notificatio_created_e3f_idx_notificatio_created_651c44_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lease', 'Lease updates'), ('mandate', 'Mandate updates'), ('rent', 'Rent & payments'), ('maintenance', 'Maintenance updates'), ('chat', 'Chat messages')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'category'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
