# Generated by Django 5.2.12 on 2026-05-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('notifications', '0003_add_push_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Backfilled null where recipient cannot be resolved.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Klikk dispatches on agency instruction (s21).', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Operational dispatch log; review at audit time.', max_length=32),
        ),
        migrations.AddField(
            model_name='pushpreference',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='push_preferences', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='pushpreference',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='consent', help_text='POPIA s11 basis. Push opt-in is consent (s11(1)(a)).', max_length=32),
        ),
        migrations.AddField(
            model_name='pushpreference',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Preference rows live with the user account.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['agency', 'created_at'], name='notif_log_agency_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='pushpreference',
            index=models.Index(fields=['agency', 'category'], name='push_pref_agency_cat_idx'),
        ),
    ]
