# Generated by Django 5.2.12 on 2026-04-06 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlisting',
            name='ai_classification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='ai_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='ai_condition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='ai_property_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='ai_style',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='canonical_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='market_data.marketlisting'),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='duplicate_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='is_duplicate',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
