# Generated by Django 5.2.12 on 2026-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_ai_classification_deduplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingagency',
            name='source',
            field=models.CharField(choices=[('property24', 'Property24'), ('private_property', 'PrivateProperty'), ('gumtree', 'Gumtree'), ('iol_property', 'IOL Property'), ('rentfind', 'RentFind'), ('pam_golding', 'Pam Golding'), ('seeff', 'Seeff'), ('facebook', 'Facebook'), ('anna_basson', 'Anna Basson Eiendomme'), ('engel_volkers', 'Engel & Völkers'), ('sothebys', "Sotheby's International Realty"), ('chas_everitt', 'Chas Everitt'), ('louw_coetzee', 'Louw & Coetzee')], max_length=30),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='source',
            field=models.CharField(choices=[('property24', 'Property24'), ('private_property', 'PrivateProperty'), ('gumtree', 'Gumtree'), ('iol_property', 'IOL Property'), ('rentfind', 'RentFind'), ('pam_golding', 'Pam Golding'), ('seeff', 'Seeff'), ('facebook', 'Facebook'), ('anna_basson', 'Anna Basson Eiendomme'), ('engel_volkers', 'Engel & Völkers'), ('sothebys', "Sotheby's International Realty"), ('chas_everitt', 'Chas Everitt'), ('louw_coetzee', 'Louw & Coetzee')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scraperun',
            name='source',
            field=models.CharField(choices=[('property24', 'Property24'), ('private_property', 'PrivateProperty'), ('gumtree', 'Gumtree'), ('iol_property', 'IOL Property'), ('rentfind', 'RentFind'), ('pam_golding', 'Pam Golding'), ('seeff', 'Seeff'), ('facebook', 'Facebook'), ('anna_basson', 'Anna Basson Eiendomme'), ('engel_volkers', 'Engel & Völkers'), ('sothebys', "Sotheby's International Realty"), ('chas_everitt', 'Chas Everitt'), ('louw_coetzee', 'Louw & Coetzee')], max_length=30),
        ),
    ]
