# Generated by Django 5.2.12 on 2026-05-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Marketing leads usually have no agency yet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_enquiries', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='consent', help_text='POPIA s11 basis. Public form opt-in = consent (s11(1)(a)).', max_length=32),
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='marketing_consent_lifetime', help_text='POPIA s14 retention. Marketing consent record (DM Guidance 2024).', max_length=32),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['agency', 'created_at'], name='contact_enq_agency_ts_idx'),
        ),
    ]
