# Generated by Django 5.2.12 on 2026-03-24 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='early_termination_penalty_months',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='lease',
            name='electricity_prepaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='max_occupants',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lease',
            name='notice_period_days',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_limit_litres',
            field=models.PositiveIntegerField(default=4000),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('signed_lease', 'Signed Lease'), ('id_copy', 'ID Copy'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='lease_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.lease')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
