# Generated by Django 5.2.12 on 2026-03-24 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_lease_ai_parse_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_tenants', to='leases.lease')),
                ('linked_user', models.ForeignKey(blank=True, help_text='System account if the co-tenant is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_tenancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_to_tenant', models.CharField(blank=True, help_text='e.g. self, spouse, child, employee, student', max_length=50)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='leases.lease')),
            ],
        ),
    ]
