# Generated by Django 5.2.12 on 2026-03-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person'),
        ('leases', '0004_cotenant_occupant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='occupant',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.AddField(
            model_name='lease',
            name='primary_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases_as_primary', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person'),
        ),
        migrations.CreateModel(
            name='LeaseGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers_tenant', models.ForeignKey(blank=True, help_text="Which tenant's obligations this guarantor covers", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_by_guarantors', to='accounts.person')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='leases.lease')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='accounts.person')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseOccupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_to_tenant', models.CharField(blank=True, help_text='e.g. self, spouse, child, employee, student', max_length=50)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='leases.lease')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='accounts.person')),
            ],
            options={
                'unique_together': {('lease', 'person')},
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_tenants', to='leases.lease')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_tenancies', to='accounts.person')),
            ],
            options={
                'unique_together': {('lease', 'person')},
            },
        ),
        migrations.DeleteModel(
            name='CoTenant',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Occupant',
        ),
    ]
