# Generated by Django 5.2.12 on 2026-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_remove_guardian_lease_remove_guardian_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
