# Generated by Django 5.2.12 on 2026-03-24 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_add_lease_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('province', models.CharField(blank=True, help_text='Leave blank for national template', max_length=100)),
                ('docx_file', models.FileField(upload_to='lease_templates/')),
                ('fields_schema', models.JSONField(default=list, help_text='List of merge field names in the template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseBuilderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, help_text='[{role, content}] conversation history')),
                ('current_state', models.JSONField(default=dict, help_text='Extracted lease field values')),
                ('rha_flags', models.JSONField(default=list, help_text='RHA compliance issues found')),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('review', 'Review'), ('finalized', 'Finalized')], default='drafting', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_builder_sessions', to=settings.AUTH_USER_MODEL)),
                ('lease', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_session', to='leases.lease')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.leasetemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
