# Generated by Django 5.2.12 on 2026-03-25 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_leasetemplate_header_footer_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reusableclause',
            name='source_templates',
            field=models.ManyToManyField(blank=True, help_text='Templates this clause was sourced from or used in', related_name='clauses', to='leases.leasetemplate'),
        ),
        migrations.CreateModel(
            name='LeaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('contract_start', 'Contract Start'), ('contract_end', 'Contract End'), ('deposit_due', 'Deposit Due'), ('first_rent', 'First Rent Due'), ('rent_due', 'Rent Due'), ('inspection_in', 'Move-in Inspection'), ('inspection_out', 'Move-out Inspection'), ('inspection_routine', 'Routine Inspection'), ('notice_deadline', 'Notice Period Deadline'), ('renewal_review', 'Renewal Review'), ('custom', 'Custom')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='upcoming', max_length=15)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for recurring events', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='leases.lease')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('deposit_payment', 'Deposit Payment'), ('lease_signed', 'Lease Signed'), ('id_verified', 'ID Verified'), ('move_in_inspection', 'Move-in Inspection'), ('key_handover', 'Key Handover'), ('invoicing_setup', 'Invoicing Setup'), ('tenant_app_setup', 'Tenant App Setup'), ('welcome_sent', 'Welcome Message Sent')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='leases.lease')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
