# Generated by Django 5.2.12 on 2026-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0011_alter_reusableclause_source_templates_leaseevent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasetemplate',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
