# Generated by Django 5.2.12 on 2026-04-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0012_add_updated_at_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='renewal_start_date',
            field=models.DateField(blank=True, help_text='Start of renewed period; dots after this date shown as unsigned/pending', null=True),
        ),
    ]
