# Generated by Django 5.2.12 on 2026-04-06 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_add_renewal_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('appliance', 'Appliance'), ('furniture', 'Furniture'), ('fixture', 'Fixture'), ('electronics', 'Electronics'), ('linen', 'Linen / Bedding'), ('kitchen', 'Kitchenware'), ('keys', 'Keys / Remotes'), ('other', 'Other')], default='other', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Description, brand, model, serial number')),
                ('condition_in', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='good', help_text='Condition at move-in', max_length=10)),
                ('condition_out', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing')], help_text='Condition at move-out', max_length=10)),
                ('photo_in', models.ImageField(blank=True, null=True, upload_to='inventory/in/')),
                ('photo_out', models.ImageField(blank=True, null=True, upload_to='inventory/out/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='leases.lease')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Furnished flat', 'Unfurnished house'", max_length=200)),
                ('items', models.JSONField(default=list, help_text='[{"name": "Fridge", "category": "appliance", "qty": 1, "notes": "Samsung 350L"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
