# Generated by Django 5.2.12 on 2026-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0014_add_inventory_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of month rent is due (1–28)'),
        ),
    ]
