# Generated by Django 5.2.12 on 2026-04-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0015_add_rent_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode / serial / asset tag', max_length=100),
        ),
    ]
