# Generated by Django 5.2.12 on 2026-05-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('leases', '0023_expire_stale_active_leases'),
        ('properties', '0031_backfill_agency_id_remaining_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='inventorytemplate',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_templates', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='inventorytemplate',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='inventorytemplate',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='lease',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Lease records never cross agencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='lease',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Lease = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='lease',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasebuildersession',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_builder_sessions', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leasebuildersession',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasebuildersession',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseevent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_events', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leaseevent',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseevent',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseguarantor',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_guarantors', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leaseguarantor',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseguarantor',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseoccupant',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_occupants', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leaseoccupant',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leaseoccupant',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Templates never cross agencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_templates', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasetemplate',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_co_tenants', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='leasetenant',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='moveinchecklistitem',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='move_in_checklist_items', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='moveinchecklistitem',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='moveinchecklistitem',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_steps', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='pdfrenderjob',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from template.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_render_jobs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='pdfrenderjob',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s21 — Klikk processes on agency operator instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='pdfrenderjob',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='System-internal render job — no automated retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='reusableclause',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Clauses never cross agencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reusable_clauses', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='reusableclause',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='reusableclause',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['agency', 'lease'], name='invitem_agency_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytemplate',
            index=models.Index(fields=['agency', 'name'], name='invtmpl_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['agency', 'status'], name='lease_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['agency', 'end_date'], name='lease_agency_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leasebuildersession',
            index=models.Index(fields=['agency', 'status'], name='builder_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['agency', 'document_type'], name='leasedoc_agency_type_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseevent',
            index=models.Index(fields=['agency', 'date'], name='leaseevent_agency_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseguarantor',
            index=models.Index(fields=['agency', 'lease'], name='guarantor_agency_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseoccupant',
            index=models.Index(fields=['agency', 'lease'], name='occupant_agency_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetemplate',
            index=models.Index(fields=['agency', 'name'], name='leasetmpl_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetenant',
            index=models.Index(fields=['agency', 'lease'], name='cotenant_agency_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='moveinchecklistitem',
            index=models.Index(fields=['agency', 'is_completed'], name='movein_agency_done_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstep',
            index=models.Index(fields=['agency', 'is_completed'], name='onboard_agency_done_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfrenderjob',
            index=models.Index(fields=['agency', 'status'], name='pdfjob_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reusableclause',
            index=models.Index(fields=['agency', 'category'], name='clause_agency_category_idx'),
        ),
    ]
