# Generated by Django 5.2.12 on 2026-05-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0026_backfill_orphans_to_agency_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetenant',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text="Payment reference for this lessee's rent EFT.", max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_reference',
            field=models.CharField(blank=True, help_text="Payment reference for the primary tenant's rent EFT. Co-tenants have their own payment_reference on LeaseTenant.", max_length=100),
        ),
    ]
