# Generated by Django 5.2.12 on 2026-05-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0027_add_payment_reference_to_lease_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leasetenant',
            options={'ordering': ['id']},
        ),
    ]
