# Generated by Django 5.2.12 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0028_lease_tenant_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='electricity_arrangement',
            field=models.CharField(choices=[('prepaid', 'Prepaid electricity'), ('eskom_direct', 'Direct Eskom account'), ('included', 'Included in rent'), ('not_included', 'Tenant arranges separately')], default='not_included', help_text='Lease-level electricity arrangement (overrides property default).', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='gardening_service_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='security_service_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='water_arrangement',
            field=models.CharField(choices=[('included', 'Water included in rent'), ('not_included', 'Water not included')], default='not_included', help_text='Lease-level water arrangement (overrides property default).', max_length=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='wifi_included',
            field=models.BooleanField(default=False),
        ),
    ]
