# Generated by Django 5.2.12 on 2026-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningsubmission',
            name='signing_mode',
            field=models.CharField(choices=[('parallel', 'Parallel — all signers at once'), ('sequential', 'Sequential — one after the other')], default='sequential', help_text='Sequential: signers proceed in order. Parallel: all sign at once.', max_length=12),
        ),
    ]
