# Generated by Django 5.2.12 on 2026-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0003_esigningpubliclink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigningpubliclink',
            name='submitter_id',
            field=models.PositiveIntegerField(help_text='DocuSeal submitter id (matches signers[].id on the submission JSON).'),
        ),
        migrations.AddIndex(
            model_name='esigningpubliclink',
            index=models.Index(fields=['expires_at'], name='esigning_es_expires_580e27_idx'),
        ),
    ]
