# Generated by Django 5.2.12 on 2026-03-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0004_alter_esigningpubliclink_submitter_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigningsubmission',
            name='signed_pdf_url',
            field=models.TextField(blank=True, help_text='URL to the signed PDF on DocuSeal (can be long)'),
        ),
    ]
