# Generated by Django 5.2.12 on 2026-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0005_widen_signed_pdf_url_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningpubliclink',
            name='signer_role',
            field=models.CharField(blank=True, help_text="Signer role for native signing (e.g. 'tenant_1', 'landlord').", max_length=50),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='document_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of document_html for tamper detection.', max_length=100),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='document_html',
            field=models.TextField(blank=True, help_text='Snapshot of filled lease HTML at submission time (native signing).'),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='signed_pdf_file',
            field=models.FileField(blank=True, help_text='Locally generated signed PDF (native signing).', upload_to='esigning/signed_pdfs/'),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='signing_backend',
            field=models.CharField(choices=[('docuseal', 'DocuSeal'), ('native', 'Native')], default='native', help_text='Which signing engine handles this submission.', max_length=10),
        ),
        migrations.AlterField(
            model_name='esigningpubliclink',
            name='submitter_id',
            field=models.PositiveIntegerField(blank=True, help_text='DocuSeal submitter id (matches signers[].id on the submission JSON).', null=True),
        ),
    ]
