# Generated by Django 5.2.12 on 2026-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0006_native_signing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningsubmission',
            name='captured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Merge field data manually entered by signers during signing.'),
        ),
    ]
