# Generated by Django 5.2.12 on 2026-04-03 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0007_esigningsubmission_captured_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningsubmission',
            name='signed_pdf_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the signed PDF for tamper detection.', max_length=100),
        ),
        migrations.CreateModel(
            name='ESigningAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('link_created', 'Link Created'), ('document_viewed', 'Document Viewed'), ('consent_given', 'Consent Given'), ('signature_applied', 'Signature Applied'), ('signing_completed', 'Signing Completed'), ('document_completed', 'Document Completed'), ('link_expired', 'Link Expired')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='esigning.esigningsubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['submission', 'event_type'], name='esigning_es_submiss_cda60b_idx')],
            },
        ),
    ]
