# Generated by Django 5.2.12 on 2026-04-05 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0008_esigningsubmission_signed_pdf_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigningauditevent',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('document_viewed', 'Document Viewed'), ('consent_given', 'Consent Given'), ('signature_applied', 'Signature Applied'), ('signing_completed', 'Signing Completed'), ('document_completed', 'Document Completed'), ('link_expired', 'Link Expired'), ('draft_saved', 'Draft Saved'), ('supporting_doc_uploaded', 'Supporting Document Uploaded'), ('supporting_doc_deleted', 'Supporting Document Deleted')], max_length=30),
        ),
        migrations.CreateModel(
            name='SigningDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_fields_data', models.JSONField(default=dict, help_text='Partially captured signature fields keyed by field name.')),
                ('captured_fields_data', models.JSONField(default=dict, help_text='Partially captured merge-field (text) values.')),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('public_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='esigning.esigningpubliclink')),
            ],
            options={
                'verbose_name': 'Signing Draft',
            },
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bank_statement', 'Bank Statement (3 months)'), ('id_copy', 'Copy of ID'), ('proof_of_address', 'Proof of Address'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(help_text='Accepted: PDF, JPEG, PNG — max 10 MB.', upload_to='esigning/supporting_docs/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by_role', models.CharField(blank=True, help_text="Signer role from ESigningPublicLink (e.g. 'tenant_1').", max_length=50)),
                ('public_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='esigning.esigningpubliclink')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='esigning.esigningsubmission')),
            ],
            options={
                'verbose_name': 'Supporting Document',
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
    ]
