# Generated by Django 5.2.12 on 2026-04-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0009_signingdraft_supportingdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esigningpubliclink',
            name='submitter_id',
        ),
        migrations.RemoveField(
            model_name='esigningsubmission',
            name='docuseal_submission_id',
        ),
        migrations.RemoveField(
            model_name='esigningsubmission',
            name='docuseal_template_id',
        ),
        migrations.RemoveField(
            model_name='esigningsubmission',
            name='signed_pdf_url',
        ),
        migrations.AlterField(
            model_name='esigningpubliclink',
            name='signer_role',
            field=models.CharField(blank=True, help_text="Signer role (e.g. 'tenant_1', 'landlord').", max_length=50),
        ),
        migrations.AlterField(
            model_name='esigningsubmission',
            name='signing_backend',
            field=models.CharField(choices=[('native', 'Native')], default='native', help_text='Which signing engine handles this submission.', max_length=10),
        ),
    ]
