# Generated by Django 5.2.12 on 2026-04-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0010_remove_docuseal_fields'),
        ('leases', '0016_add_barcode_to_inventory'),
        ('properties', '0017_add_rental_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningsubmission',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_submissions', to='properties.rentalmandate'),
        ),
        migrations.AlterField(
            model_name='esigningsubmission',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_submissions', to='leases.lease'),
        ),
    ]
