# Generated by Django 5.2.12 on 2026-05-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('esigning', '0011_add_rental_mandate'),
        ('leases', '0025_backfill_agency_id_leases'),
        ('properties', '0031_backfill_agency_id_remaining_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esigningauditevent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from submission.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esigning_audit_events', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='esigningauditevent',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Contractual signing audit trail.', max_length=32),
        ),
        migrations.AddField(
            model_name='esigningauditevent',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. ECTA s13 evidence — keep with lease.', max_length=32),
        ),
        migrations.AddField(
            model_name='esigningpubliclink',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from submission.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esigning_public_links', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='esigningpubliclink',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Short-lived signing token (operator instruction).', max_length=32),
        ),
        migrations.AddField(
            model_name='esigningpubliclink',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Tokens auto-expire on submission/timeout.', max_length=32),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from lease/mandate chain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esigning_submissions', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Lease signing = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='esigningsubmission',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Signed PDF inherits lease retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='signingdraft',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from public_link.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esigning_drafts', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='signingdraft',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Partial-signing state for contract performance.', max_length=32),
        ),
        migrations.AddField(
            model_name='signingdraft',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Discarded once submission completes.', max_length=32),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from submission.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='esigning_supporting_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. FICA/KYC docs = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention. FICA s42/s43 5-year minimum.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='esigningauditevent',
            index=models.Index(fields=['agency', 'event_type'], name='esign_evt_agency_type_idx'),
        ),
        migrations.AddIndex(
            model_name='esigningpubliclink',
            index=models.Index(fields=['agency', 'expires_at'], name='esign_link_agency_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='esigningsubmission',
            index=models.Index(fields=['agency', 'status'], name='esign_sub_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='signingdraft',
            index=models.Index(fields=['agency', 'saved_at'], name='esign_draft_agency_saved_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['agency', 'document_type'], name='esign_supdoc_agency_typ_idx'),
        ),
    ]
