# Generated by Django 5.2.12 on 2026-05-07 21:32
#
# QA Round 3 (B): close ESigning concurrent-submission race.
# Before adding the partial unique constraint, deduplicate any pre-existing
# violations: per (lease_id) where status=pending, keep the most-recent row
# and mark older siblings as expired so historical audit data is preserved.

from django.conf import settings
from django.db import migrations, models


def dedupe_pending_submissions(apps, schema_editor):
    ESigningSubmission = apps.get_model("esigning", "ESigningSubmission")
    from django.db.models import Count

    dup_lease_ids = (
        ESigningSubmission.objects
        .filter(status="pending", lease__isnull=False)
        .values("lease_id")
        .annotate(c=Count("id"))
        .filter(c__gt=1)
        .values_list("lease_id", flat=True)
    )
    for lease_id in dup_lease_ids:
        rows = list(
            ESigningSubmission.objects
            .filter(lease_id=lease_id, status="pending")
            .order_by("-created_at", "-id")
        )
        # keep newest, mark the rest expired
        for stale in rows[1:]:
            stale.status = "expired"
            stale.save(update_fields=["status", "updated_at"])


def noop_reverse(apps, schema_editor):
    # Cannot resurrect dedup'd rows; reversing the constraint is enough.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_backfill_orphan_users_to_agency_1'),
        ('esigning', '0014_backfill_orphans_to_agency_1'),
        ('leases', '0028_lease_tenant_ordering'),
        ('properties', '0032_backfill_orphans_to_agency_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_pending_submissions, noop_reverse),
        migrations.AddConstraint(
            model_name='esigningsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('lease__isnull', False)), fields=('lease',), name='unique_pending_submission_per_lease'),
        ),
    ]
