# Generated by Django 5.2.12 on 2026-04-15 12:34

import apps.the_volt.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('org_contact_email', models.EmailField(blank=True, max_length=254)),
                ('api_key_hash', models.CharField(help_text='SHA-256 of the raw API key', max_length=128)),
                ('api_key_prefix', models.CharField(help_text='First chars of raw key (display only)', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Subscriber',
                'verbose_name_plural': 'Data Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(help_text='Encrypted .enc bytes', upload_to=apps.the_volt.documents.models.vault_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(help_text='Pre-encryption plaintext size in bytes')),
                ('sha256_hash', models.CharField(help_text='SHA-256 of plaintext bytes', max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('chroma_id', models.CharField(blank=True, help_text='ChromaDB base chunk ID in volt_documents', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('personal', 'Personal'), ('trust', 'Trust'), ('company', 'Company'), ('close_corporation', 'Close Corporation'), ('sole_proprietary', 'Sole Proprietary'), ('asset', 'Asset')], max_length=30)),
                ('name', models.CharField(help_text="Human label, e.g. 'John Smith', 'Acme (Pty) Ltd'", max_length=255)),
                ('data', models.JSONField(default=dict, help_text='Type-specific structured fields per DATA_SCHEMAS')),
                ('chroma_id', models.CharField(blank=True, help_text='ChromaDB base ID in volt_entities', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vault Entity',
                'verbose_name_plural': 'Vault Entities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('requested_entity_types', models.JSONField(default=list, help_text="e.g. ['personal', 'company']")),
                ('requested_fields', models.JSONField(default=dict, help_text="e.g. {'personal': ['id_number', 'address']} or {'*': ['*']} for all")),
                ('requested_document_types', models.JSONField(default=list, help_text="e.g. ['id_document', 'proof_of_address']")),
                ('purpose', models.TextField(help_text='Human-readable reason shown to the owner for consent')),
                ('expires_at', models.DateTimeField(help_text='Auto: 48h from creation')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='the_volt.datasubscriber')),
            ],
            options={
                'verbose_name': 'Data Request',
                'verbose_name_plural': 'Data Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entities_shared', models.JSONField(help_text='[{entity_id, entity_type, name}, ...]')),
                ('documents_shared', models.JSONField(help_text='[{version_id, document_type, filename}, ...]')),
                ('data_hash', models.CharField(help_text='SHA-256 of the full data package bytes', max_length=64)),
                ('package_signature', models.CharField(help_text='HMAC-SHA256 signature of package', max_length=128)),
                ('delivery_method', models.CharField(choices=[('rest', 'REST API'), ('mcp', 'MCP'), ('graphql', 'GraphQL'), ('internal', 'Internal (app module)')], max_length=20)),
                ('authorisation_method', models.CharField(choices=[('owner_approved', 'Owner Approved'), ('auto_grant', 'Auto Grant (internal)')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, help_text='Null for internal gateway access (no external DataRequest)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='the_volt.datarequest')),
            ],
            options={
                'verbose_name': 'Data Checkout',
                'verbose_name_plural': 'Data Checkouts',
                'ordering': ['-checked_out_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequestApprovalLink',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(help_text='SHA-256 of the 6-digit OTP', max_length=64)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_link', to='the_volt.datarequest')),
            ],
            options={
                'verbose_name': 'Approval Link',
                'verbose_name_plural': 'Approval Links',
            },
        ),
        migrations.CreateModel(
            name='EntitySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('personal', 'Personal'), ('trust', 'Trust'), ('company', 'Company'), ('close_corporation', 'Close Corporation'), ('sole_proprietary', 'Sole Proprietary'), ('asset', 'Asset')], max_length=30)),
                ('country_code', models.CharField(default='ZA', help_text="ISO 3166-1 alpha-2 country code. 'ZA' = South Africa.", max_length=2)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(help_text="Human label for this entity type, e.g. 'South African Company'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Guidance shown above the form')),
                ('fields', models.JSONField(default=list, help_text='Ordered list of field definition objects (see module docstring for format)')),
                ('is_active', models.BooleanField(default=True, help_text='Only one schema per (entity_type, country_code) can be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Schema',
                'verbose_name_plural': 'Entity Schemas',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['entity_type', 'country_code', 'is_active'], name='the_volt_en_entity__9dba57_idx')],
                'unique_together': {('entity_type', 'country_code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_document', 'ID Document'), ('passport', 'Passport'), ('proof_of_address', 'Proof of Address'), ('trust_deed', 'Trust Deed'), ('moi', 'Memorandum of Incorporation'), ('cipc_certificate', 'CIPC Certificate'), ('tax_clearance', 'Tax Clearance'), ('financial_statement', 'Financial Statement'), ('title_deed', 'Title Deed'), ('insurance_policy', 'Insurance Policy'), ('fica_document', 'FICA Document'), ('banking_detail', 'Banking Detail'), ('resolution', 'Resolution'), ('power_of_attorney', 'Power of Attorney'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(help_text='e.g. "John\'s SA ID"', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.ForeignKey(blank=True, help_text='Pointer to the latest DocumentVersion, updated atomically by signal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='the_volt.documentversion')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='the_volt.vaultentity')),
            ],
            options={
                'verbose_name': 'Vault Document',
                'verbose_name_plural': 'Vault Documents',
                'ordering': ['-created_at'],
                'unique_together': {('entity', 'document_type', 'label')},
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='the_volt.vaultdocument'),
        ),
        migrations.CreateModel(
            name='VaultOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Owner',
                'verbose_name_plural': 'Vault Owners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vaultentity',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='the_volt.vaultowner'),
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('director_of', 'Director of'), ('trustee_of', 'Trustee of'), ('beneficial_owner_of', 'Beneficial Owner of'), ('member_of', 'Member of'), ('shareholder_of', 'Shareholder of'), ('holds_asset', 'Holds Asset'), ('operates_as', 'Operates As'), ('guarantor_for', 'Guarantor For')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional: share_pct, effective_date, end_date, notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='the_volt.vaultentity')),
                ('to_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='the_volt.vaultentity')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='the_volt.vaultowner')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datarequest',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='the_volt.vaultowner'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='vaultentity',
            index=models.Index(fields=['vault', 'entity_type'], name='the_volt_va_vault_i_2ec2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultentity',
            index=models.Index(fields=['vault', 'is_active'], name='the_volt_va_vault_i_883f3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelationship',
            unique_together={('from_entity', 'to_entity', 'relationship_type')},
        ),
    ]
