# Generated by Django 5.2.12 on 2026-04-15 12:43

import apps.the_volt.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_volt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Client-supplied OCR / structured extraction of this document (e.g. parsed Memorandum of Incorporation fields). Used directly for ChromaDB indexing — no server-side re-extraction.'),
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('self_attested', 'Self-attested'), ('commissioner_signed', 'Commissioner of Oaths Signed'), ('third_party_verified', 'Third-party Verified'), ('official_source', 'Verified against Official Source'), ('rejected', 'Rejected')], default='unverified', max_length=30)),
                ('verification_source', models.CharField(blank=True, help_text="Free-text source (e.g. 'Home Affairs HANIS', 'CIPC BizPortal', commissioner's office)", max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Name or identifier of the verifier (user, commissioner, integration)', max_length=255)),
                ('commissioner_name', models.CharField(blank=True, max_length=255)),
                ('commissioner_reference', models.CharField(blank=True, help_text='Commissioner ID / registration / stamp reference', max_length=100)),
                ('commissioner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('certified_copy_file', models.FileField(blank=True, help_text='Encrypted bytes of the commissioner-signed / certified copy', null=True, upload_to=apps.the_volt.documents.models.certified_copy_upload_path)),
                ('certified_copy_sha256', models.CharField(blank=True, help_text='SHA-256 of the certified copy plaintext bytes', max_length=64)),
                ('certified_copy_original_filename', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.DateField(blank=True, help_text='When the document itself expires (e.g. passport expiry)', null=True)),
                ('verification_metadata', models.JSONField(blank=True, default=dict, help_text='Free-form extras: OCR confidence, API response, notes, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='the_volt.documentversion')),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
            },
        ),
        migrations.CreateModel(
            name='EntityDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text="Matches a key in DATA_SCHEMAS / EntitySchema (e.g. 'id_number')", max_length=100)),
                ('value', models.JSONField(help_text='The field value (string/number/list/dict)')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('self_attested', 'Self-attested'), ('document_backed', 'Backed by Verified Document'), ('official_source', 'Verified against Official Source'), ('rejected', 'Rejected')], default='unverified', max_length=30)),
                ('verification_source', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255)),
                ('extraction_source', models.CharField(choices=[('client_ocr', 'Client-side OCR'), ('manual_entry', 'Manual Entry'), ('api_lookup', 'External API Lookup'), ('ai_extraction', 'Server AI Extraction')], default='manual_entry', max_length=30)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('chroma_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='the_volt.vaultentity')),
                ('source_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_fields', to='the_volt.documentversion')),
            ],
            options={
                'verbose_name': 'Entity Data Field',
                'verbose_name_plural': 'Entity Data Fields',
                'ordering': ['entity', 'field_key'],
                'unique_together': {('entity', 'field_key')},
            },
        ),
    ]
