# Generated by Django 5.2.12 on 2026-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_volt', '0002_documentversion_extracted_data_documentverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Stable machine code, e.g. 'cipc_cor14_3', 'sa_id_document'", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human label, e.g. 'CIPC CoR14.3 Registration Certificate'", max_length=255)),
                ('external_reference_codes', models.JSONField(blank=True, default=list, help_text="Alternative names / regulatory form numbers, e.g. ['CoR14.3', 'Registration Certificate']")),
                ('applies_to_entity_types', models.JSONField(default=list, help_text="EntityType codes this document can attach to, e.g. ['company'] or ['personal', 'sole_proprietary']")),
                ('ownership_scope', models.CharField(choices=[('asset_bound', 'Asset-bound (transfers with asset)'), ('owner_bound', 'Owner-bound (stays with owner)'), ('shared', 'Shared (dual-vaulted)')], default='owner_bound', help_text='Asset-bound docs transfer on sale; owner-bound stay with the owner', max_length=20)),
                ('issuing_authority', models.CharField(blank=True, help_text="e.g. 'CIPC', 'DHA', 'SARS', 'Master of the High Court', 'Deeds Office'", max_length=100)),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text='Typical validity window (e.g. 90 for proof of address, 365 for tax clearance). Null = no expiry', null=True)),
                ('email_sender_patterns', models.JSONField(blank=True, default=list, help_text="Sender email patterns, e.g. ['*@cipc.co.za', 'noreply@sarsefiling.co.za']")),
                ('email_subject_patterns', models.JSONField(blank=True, default=list, help_text='Subject substrings that indicate this doc type')),
                ('classification_signals', models.TextField(blank=True, help_text='Free-text hints for an AI classifier: distinguishing phrases, layout cues, stamps')),
                ('extraction_schema', models.JSONField(blank=True, default=dict, help_text='Expected extraction fields: {field_key: {type, label, required}}')),
                ('is_primary_identity_doc', models.BooleanField(default=False, help_text='True for SA ID, passport, CIPC registration — docs that establish identity')),
                ('regulatory_reference', models.CharField(blank=True, help_text="Legal basis, e.g. 'FICA s.21', 'Companies Act s.14', 'Trust Property Control Act'", max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within an entity type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Type (Catalogue)',
                'verbose_name_plural': 'Document Type Catalogue',
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['is_active'], name='the_volt_do_is_acti_81af66_idx'), models.Index(fields=['ownership_scope'], name='the_volt_do_ownersh_30d09b_idx')],
            },
        ),
    ]
