# Generated by Django 5.2.12 on 2026-04-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_volt', '0003_documenttypecatalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('director_of', 'Director of'), ('trustee_of', 'Trustee of'), ('beneficial_owner_of', 'Beneficial Owner of'), ('member_of', 'Member of'), ('shareholder_of', 'Shareholder of'), ('holds_asset', 'Holds Asset'), ('operates_as', 'Operates As'), ('guarantor_for', 'Guarantor For'), ('leases_from', 'Leases From'), ('parent_of', 'Parent Of')], max_length=40),
        ),
        migrations.CreateModel(
            name='VaultOwnerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Human label, e.g. 'Claude Desktop — MacBook', 'Gmail importer'", max_length=100)),
                ('api_key_hash', models.CharField(help_text='SHA-256 of the raw API key (hex)', max_length=64, unique=True)),
                ('api_key_prefix', models.CharField(help_text="First chars of raw key for display, e.g. 'volt_owner_abc12…'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vault_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='the_volt.vaultowner')),
            ],
            options={
                'verbose_name': 'Vault Owner API Key',
                'verbose_name_plural': 'Vault Owner API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultWriteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('ensure_vault', 'Ensure vault exists'), ('upsert_owner', 'Upsert owner entity'), ('upsert_property', 'Upsert property asset'), ('upsert_tenant', 'Upsert tenant entity'), ('upsert_entity', 'Upsert generic entity'), ('attach_document', 'Attach document version'), ('link_entities', 'Link two entities'), ('unlink_entities', 'Unlink two entities')], max_length=40)),
                ('target_model', models.CharField(help_text="e.g. 'VaultEntity', 'VaultDocument', 'EntityRelationship'", max_length=60)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='PK of the affected row. Null if multiple or pre-create', null=True)),
                ('before', models.JSONField(blank=True, default=dict, help_text='Changed fields, pre-mutation. Empty on create.')),
                ('after', models.JSONField(blank=True, default=dict, help_text='Changed fields, post-mutation. Empty on delete.')),
                ('client_info', models.JSONField(blank=True, default=dict, help_text='Free-form metadata: MCP client name, tool name, args hash, ip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, help_text='Which owner API key performed the write (null = internal caller)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='the_volt.vaultownerapikey')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_audits', to='the_volt.vaultowner')),
            ],
            options={
                'verbose_name': 'Vault Write Audit',
                'verbose_name_plural': 'Vault Write Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultownerapikey',
            index=models.Index(fields=['api_key_hash'], name='the_volt_va_api_key_346837_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultownerapikey',
            index=models.Index(fields=['vault_owner', 'is_active'], name='the_volt_va_vault_o_2406f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultwriteaudit',
            index=models.Index(fields=['vault', '-created_at'], name='the_volt_va_vault_i_bd3c41_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultwriteaudit',
            index=models.Index(fields=['api_key', '-created_at'], name='the_volt_va_api_key_b7a8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultwriteaudit',
            index=models.Index(fields=['operation'], name='the_volt_va_operati_62ff3c_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultwriteaudit',
            index=models.Index(fields=['target_model', 'target_id'], name='the_volt_va_target__5a9e60_idx'),
        ),
    ]
