# Generated by Django 5.2.12 on 2026-04-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_volt', '0005_seed_document_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipTypeCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Stable machine code, e.g. 'director_of', 'leases_from'", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Forward label: 'Director of'", max_length=255)),
                ('inverse_label', models.CharField(blank=True, help_text="Reverse label for UI: 'Has Director'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Plain-English explanation of what this relationship means')),
                ('valid_from_entity_types', models.JSONField(blank=True, default=list, help_text='Entity type codes allowed as source node. Empty = any.')),
                ('valid_to_entity_types', models.JSONField(blank=True, default=list, help_text='Entity type codes allowed as target node. Empty = any.')),
                ('metadata_schema', models.JSONField(blank=True, default=dict, help_text='Hints for metadata fields: {field_key: {type, label, required}}')),
                ('regulatory_reference', models.CharField(blank=True, help_text="e.g. 'FICA s.21 beneficial ownership', 'Companies Act s.69'", max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='True = seeded by migration; cannot be deleted via API')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relationship Type (Catalogue)',
                'verbose_name_plural': 'Relationship Type Catalogue',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='entityrelationship',
            name='relationship_type',
            field=models.ForeignKey(help_text="References RelationshipTypeCatalogue — create the type first if it doesn't exist", on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='the_volt.relationshiptypecatalogue'),
        ),
    ]
