# Generated by Django 5.2.12 on 2026-04-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_volt', '0006_seed_asset_documents'),
        ('the_volt', '0007_seed_relationship_types'),
    ]

    operations = [
    ]
