from django.db import migrations

# Company, Trust, Close Corporation, Sole Proprietary entries
# (These were added to 0005 after it was already applied, so they live here instead)

DOCUMENTS = [
    # ── Company (sort_order 200-219) ─────────────────────────────────────────
    {
        "code": "cipc_cor14_3",
        "label": "CIPC CoR14.3 Registration Certificate",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": True,
        "regulatory_reference": "Companies Act s.14",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 200,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": ["Registration Certificate", "CoR 14.3"],
        "external_reference_codes": ["CoR14.3", "Registration Certificate"],
        "is_active": True,
        "classification_signals": "CIPC registration certificate with company registration number in format YYYY/NNNNNN/NN. Company type (Pty Ltd, NPC, etc). CIPC letterhead.",
        "extraction_schema": {
            "company_name":        {"type": "string", "label": "Company Name",        "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "registration_date":   {"type": "date",   "label": "Registration Date",   "required": True},
            "company_type":        {"type": "string", "label": "Company Type",        "required": True},
        },
    },
    {
        "code": "cipc_cor14_1",
        "label": "CIPC CoR14.1 Notice of Incorporation",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.13",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 201,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": [],
        "external_reference_codes": ["CoR14.1"],
        "is_active": True,
        "classification_signals": "Notice of Incorporation. Lists initial directors and registered address. CIPC reference number.",
        "extraction_schema": {
            "company_name":       {"type": "string", "label": "Company Name",        "required": True},
            "directors":          {"type": "list",   "label": "Initial Directors",   "required": False},
            "registered_address": {"type": "text",   "label": "Registered Address",  "required": False},
        },
    },
    {
        "code": "cipc_cor14_1a",
        "label": "CIPC CoR14.1A Notice of Amendment",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.16",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 202,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": [],
        "external_reference_codes": ["CoR14.1A"],
        "is_active": True,
        "classification_signals": "Notice of amendment to MOI or company details. References original registration number.",
        "extraction_schema": {
            "company_name":        {"type": "string", "label": "Company Name",        "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "amendment_type":      {"type": "string", "label": "Amendment Type",      "required": False},
            "effective_date":      {"type": "date",   "label": "Effective Date",      "required": False},
        },
    },
    {
        "code": "cipc_cor39",
        "label": "CIPC CoR39 Registered Office Change",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.23",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 203,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": [],
        "external_reference_codes": ["CoR39"],
        "is_active": True,
        "classification_signals": "CIPC CoR39 form confirming new registered office address. Company registration number and new address.",
        "extraction_schema": {
            "company_name":        {"type": "string", "label": "Company Name",             "required": True},
            "registration_number": {"type": "string", "label": "Registration Number",      "required": True},
            "new_address":         {"type": "text",   "label": "New Registered Address",   "required": True},
            "effective_date":      {"type": "date",   "label": "Effective Date",           "required": False},
        },
    },
    {
        "code": "moi",
        "label": "Memorandum of Incorporation (MOI)",
        "issuing_authority": "Company",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.15",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 204,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": ["MOI", "Memorandum of Incorporation"],
        "is_active": True,
        "classification_signals": "MOI document. Contains share capital structure, director powers, restrictive conditions. May be notarised.",
        "extraction_schema": {
            "company_name":            {"type": "string", "label": "Company Name",             "required": True},
            "registration_number":     {"type": "string", "label": "Registration Number",      "required": False},
            "share_classes":           {"type": "list",   "label": "Share Classes",            "required": False},
            "restrictive_conditions":  {"type": "text",   "label": "Restrictive Conditions",   "required": False},
        },
    },
    {
        "code": "bo_register",
        "label": "Beneficial Ownership Register",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.56; General Laws Amendment Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation"],
        "sort_order": 205,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": ["BO Register", "Beneficial Ownership Register"],
        "is_active": True,
        "classification_signals": "CIPC beneficial ownership register filing. Lists natural persons who ultimately own or control the entity.",
        "extraction_schema": {
            "company_name":      {"type": "string", "label": "Company Name",       "required": True},
            "beneficial_owners": {"type": "list",   "label": "Beneficial Owners",  "required": True},
            "percentage_held":   {"type": "dict",   "label": "Ownership %",        "required": False},
            "date_updated":      {"type": "date",   "label": "Date Updated",       "required": False},
        },
    },
    {
        "code": "securities_register",
        "label": "Securities Register",
        "issuing_authority": "Company",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.50",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 206,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Securities/share register maintained by company. Lists shareholders, shares held, share class, transfer history.",
        "extraction_schema": {
            "company_name": {"type": "string", "label": "Company Name",  "required": True},
            "shareholders": {"type": "list",   "label": "Shareholders",  "required": True},
            "shares_held":  {"type": "dict",   "label": "Shares Held",   "required": False},
            "share_class":  {"type": "string", "label": "Share Class",   "required": False},
        },
    },
    {
        "code": "annual_return",
        "label": "CIPC Annual Return (CoR30.1)",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.33",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 207,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": ["Annual Return", "CoR30"],
        "external_reference_codes": ["CoR30.1", "Annual Return"],
        "is_active": True,
        "classification_signals": "CIPC annual return filing confirmation. Financial year end, filing date, fee paid, compliance status.",
        "extraction_schema": {
            "company_name":        {"type": "string", "label": "Company Name",        "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "financial_year_end":  {"type": "string", "label": "Financial Year End",  "required": False},
            "filing_date":         {"type": "date",   "label": "Filing Date",         "required": False},
        },
    },
    {
        "code": "tax_clearance_company",
        "label": "Tax Clearance Certificate (Company)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Tax Administration Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "sole_proprietary"],
        "sort_order": 208,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": ["Tax Clearance", "Tax Compliance"],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS tax clearance or compliance status document. Entity tax number, valid period, compliance status.",
        "extraction_schema": {
            "company_name": {"type": "string", "label": "Entity Name",         "required": True},
            "tax_number":   {"type": "string", "label": "Tax Number",          "required": True},
            "valid_from":   {"type": "date",   "label": "Valid From",          "required": True},
            "valid_to":     {"type": "date",   "label": "Valid To",            "required": True},
            "status":       {"type": "string", "label": "Compliance Status",   "required": True},
        },
    },
    {
        "code": "vat_registration",
        "label": "VAT Registration Certificate",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "VAT Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "sole_proprietary", "trust"],
        "sort_order": 209,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS VAT registration certificate. VAT number starting with 4, entity name, registration date.",
        "extraction_schema": {
            "entity_name":       {"type": "string", "label": "Registered Name",   "required": True},
            "vat_number":        {"type": "string", "label": "VAT Number",        "required": True},
            "registration_date": {"type": "date",   "label": "Registration Date", "required": False},
            "category":          {"type": "string", "label": "VAT Category",      "required": False},
        },
    },
    {
        "code": "bbbee_certificate",
        "label": "B-BBEE Certificate / Affidavit",
        "issuing_authority": "SANAS-accredited agency",
        "is_primary_identity_doc": False,
        "regulatory_reference": "B-BBEE Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "sole_proprietary"],
        "sort_order": 210,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "B-BBEE verification certificate. Level (1-8 or Non-Compliant), scorecard, valid period. May be a sworn affidavit for EME/QSE.",
        "extraction_schema": {
            "entity_name":        {"type": "string", "label": "Entity Name",          "required": True},
            "bbbee_level":        {"type": "string", "label": "B-BBEE Level",         "required": True},
            "valid_from":         {"type": "date",   "label": "Valid From",           "required": True},
            "valid_to":           {"type": "date",   "label": "Valid To",             "required": True},
            "verification_agency":{"type": "string", "label": "Verification Agency",  "required": False},
        },
    },
    {
        "code": "auditors_report",
        "label": "Auditor's Report / Independent Review",
        "issuing_authority": "Registered Auditor",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.90",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation"],
        "sort_order": 211,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Auditor's report on auditing firm letterhead. Opinion type (unqualified/qualified/adverse). Signed by registered auditor.",
        "extraction_schema": {
            "entity_name":    {"type": "string", "label": "Entity Name",      "required": True},
            "financial_year": {"type": "string", "label": "Financial Year",   "required": True},
            "auditor_name":   {"type": "string", "label": "Auditor Name",     "required": True},
            "opinion_type":   {"type": "string", "label": "Opinion Type",     "required": True},
            "date_signed":    {"type": "date",   "label": "Date Signed",      "required": False},
        },
    },
    {
        "code": "shareholder_resolution",
        "label": "Shareholders' Resolution",
        "issuing_authority": "Company",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.65",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 212,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Shareholders resolution headed 'Resolution of Shareholders'. Lists shareholders present, resolution text, signatures.",
        "extraction_schema": {
            "company_name":    {"type": "string", "label": "Company Name",     "required": True},
            "resolution_type": {"type": "string", "label": "Resolution Type",  "required": False},
            "date_passed":     {"type": "date",   "label": "Date Passed",      "required": True},
            "signatories":     {"type": "list",   "label": "Signatories",      "required": False},
        },
    },
    {
        "code": "directors_resolution",
        "label": "Directors' Resolution",
        "issuing_authority": "Company",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.73",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 213,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Board resolution or round-robin resolution. 'Resolution of the Board of Directors'. Directors present, resolution text.",
        "extraction_schema": {
            "company_name":       {"type": "string", "label": "Company Name",       "required": True},
            "resolution_subject": {"type": "string", "label": "Resolution Subject", "required": False},
            "date_passed":        {"type": "date",   "label": "Date Passed",        "required": True},
            "directors_present":  {"type": "list",   "label": "Directors Present",  "required": False},
        },
    },
    {
        "code": "company_bank_confirmation",
        "label": "Bank Confirmation Letter (Company)",
        "issuing_authority": "Bank",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 214,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Bank letterhead confirming company account details. Registered company name, account number, branch code, account type.",
        "extraction_schema": {
            "company_name":   {"type": "string", "label": "Company Name",    "required": True},
            "bank_name":      {"type": "string", "label": "Bank Name",       "required": True},
            "account_number": {"type": "string", "label": "Account Number",  "required": True},
            "branch_code":    {"type": "string", "label": "Branch Code",     "required": True},
            "account_type":   {"type": "string", "label": "Account Type",    "required": False},
            "date_issued":    {"type": "date",   "label": "Date Issued",     "required": True},
        },
    },
    {
        "code": "coida_certificate",
        "label": "COIDA Letter of Good Standing",
        "issuing_authority": "Compensation Fund",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Compensation for Occupational Injuries and Diseases Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "sole_proprietary"],
        "sort_order": 215,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Compensation Fund letter of good standing. CF registration number, employer name, valid period.",
        "extraction_schema": {
            "entity_name":        {"type": "string", "label": "Employer Name",      "required": True},
            "registration_number":{"type": "string", "label": "CF Reg Number",      "required": True},
            "valid_from":         {"type": "date",   "label": "Valid From",         "required": True},
            "valid_to":           {"type": "date",   "label": "Valid To",           "required": True},
        },
    },
    {
        "code": "uif_registration",
        "label": "UIF Registration Letter",
        "issuing_authority": "Department of Employment and Labour",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Unemployment Insurance Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "sole_proprietary"],
        "sort_order": 216,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "UIF registration confirmation. UI Reference number, employer name, registration date.",
        "extraction_schema": {
            "entity_name":       {"type": "string", "label": "Employer Name",       "required": True},
            "uif_reference":     {"type": "string", "label": "UI Reference Number", "required": True},
            "registration_date": {"type": "date",   "label": "Registration Date",   "required": False},
        },
    },
    {
        "code": "cipc_disclosure",
        "label": "CIPC Disclosure Certificate",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.26",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation"],
        "sort_order": 217,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "CIPC disclosure / company info printout. Current directors, registered address, company status, financial year end.",
        "extraction_schema": {
            "company_name":        {"type": "string", "label": "Company Name",        "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "directors":           {"type": "list",   "label": "Directors",           "required": False},
            "registered_address":  {"type": "text",   "label": "Registered Address",  "required": False},
            "status":              {"type": "string", "label": "Company Status",      "required": False},
        },
    },
    {
        "code": "financial_statements",
        "label": "Annual Financial Statements",
        "issuing_authority": "Company / Auditor",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.28-30",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company", "close_corporation", "trust", "sole_proprietary"],
        "sort_order": 218,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Annual financial statements. Balance sheet, income statement, cash flow. Signed by director and auditor/accountant.",
        "extraction_schema": {
            "entity_name":      {"type": "string",  "label": "Entity Name",           "required": True},
            "financial_year":   {"type": "string",  "label": "Financial Year",        "required": True},
            "total_assets":     {"type": "decimal", "label": "Total Assets",          "required": False},
            "total_liabilities":{"type": "decimal", "label": "Total Liabilities",     "required": False},
            "revenue":          {"type": "decimal", "label": "Revenue",               "required": False},
            "net_income":       {"type": "decimal", "label": "Net Income / (Loss)",   "required": False},
        },
    },
    {
        "code": "share_certificate",
        "label": "Share Certificate",
        "issuing_authority": "Company",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Companies Act s.51",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["company"],
        "sort_order": 219,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Share certificate issued by company. Certificate number, shareholder name, number of shares, share class, date issued. Company seal.",
        "extraction_schema": {
            "company_name":       {"type": "string",  "label": "Company Name",      "required": True},
            "shareholder_name":   {"type": "string",  "label": "Shareholder Name",  "required": True},
            "shares_held":        {"type": "integer", "label": "Shares Held",       "required": True},
            "share_class":        {"type": "string",  "label": "Share Class",       "required": False},
            "certificate_number": {"type": "string",  "label": "Certificate Number","required": False},
            "date_issued":        {"type": "date",    "label": "Date Issued",       "required": True},
        },
    },

    # ── Trust (sort_order 300-312) ────────────────────────────────────────────
    {
        "code": "trust_deed",
        "label": "Trust Deed",
        "issuing_authority": "Founder / Notary",
        "is_primary_identity_doc": True,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 300,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Trust deed. Contains trust name, founder details, trustee appointments, beneficiary classes, trust objectives. Usually notarised.",
        "extraction_schema": {
            "trust_name":   {"type": "string", "label": "Trust Name",    "required": True},
            "trust_number": {"type": "string", "label": "IT Number",     "required": False},
            "trust_type":   {"type": "string", "label": "Trust Type",    "required": False},
            "founder_name": {"type": "string", "label": "Founder Name",  "required": True},
            "trustees":     {"type": "list",   "label": "Trustees",      "required": True},
            "beneficiaries":{"type": "list",   "label": "Beneficiaries", "required": False},
            "date_created": {"type": "date",   "label": "Date Created",  "required": False},
        },
    },
    {
        "code": "letters_of_authority",
        "label": "Letters of Authority (Trust)",
        "issuing_authority": "Master of the High Court",
        "is_primary_identity_doc": True,
        "regulatory_reference": "Trust Property Control Act s.6",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 301,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": ["LoA", "Letters of Authority"],
        "is_active": True,
        "classification_signals": "Letters of Authority from Master of the High Court. IT number, authorised trustees, Master's stamp.",
        "extraction_schema": {
            "trust_name":          {"type": "string", "label": "Trust Name",              "required": True},
            "trust_number":        {"type": "string", "label": "IT Number",               "required": True},
            "trustees_authorised": {"type": "list",   "label": "Authorised Trustees",     "required": True},
            "master_reference":    {"type": "string", "label": "Master's Reference",      "required": False},
            "date_issued":         {"type": "date",   "label": "Date Issued",             "required": True},
        },
    },
    {
        "code": "trustee_id_copies",
        "label": "Certified ID Copies — Trustees",
        "issuing_authority": "DHA / Commissioner of Oaths",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 302,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Commissioner of Oaths certified copies of trustee ID documents. Certification stamp and commissioner details.",
        "extraction_schema": {
            "trustee_names": {"type": "list", "label": "Trustee Names", "required": True},
            "id_numbers":    {"type": "list", "label": "ID Numbers",    "required": False},
        },
    },
    {
        "code": "trust_resolution",
        "label": "Trust Resolution",
        "issuing_authority": "Trustees",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 303,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Trustees resolution headed 'Resolution of Trustees'. Trust name and IT number. Signatures of all trustees.",
        "extraction_schema": {
            "trust_name":        {"type": "string", "label": "Trust Name",        "required": True},
            "resolution_subject":{"type": "string", "label": "Resolution Subject","required": False},
            "date_passed":       {"type": "date",   "label": "Date Passed",       "required": True},
            "trustees_present":  {"type": "list",   "label": "Trustees Present",  "required": False},
        },
    },
    {
        "code": "trust_bank_confirmation",
        "label": "Bank Confirmation Letter (Trust)",
        "issuing_authority": "Bank",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 304,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Bank letterhead confirming trust bank account. Trust name, account number, branch code, account type.",
        "extraction_schema": {
            "trust_name":     {"type": "string", "label": "Trust Name",     "required": True},
            "bank_name":      {"type": "string", "label": "Bank Name",      "required": True},
            "account_number": {"type": "string", "label": "Account Number", "required": True},
            "branch_code":    {"type": "string", "label": "Branch Code",    "required": True},
            "account_type":   {"type": "string", "label": "Account Type",   "required": False},
            "date_issued":    {"type": "date",   "label": "Date Issued",    "required": True},
        },
    },
    {
        "code": "trust_tax_clearance",
        "label": "Tax Clearance Certificate (Trust)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Tax Administration Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 305,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS tax clearance for a trust. Trust tax number, valid period, compliance status.",
        "extraction_schema": {
            "trust_name": {"type": "string", "label": "Trust Name",        "required": True},
            "tax_number": {"type": "string", "label": "Tax Number",        "required": True},
            "valid_from": {"type": "date",   "label": "Valid From",        "required": True},
            "valid_to":   {"type": "date",   "label": "Valid To",          "required": True},
            "status":     {"type": "string", "label": "Compliance Status", "required": True},
        },
    },
    {
        "code": "beneficiary_list",
        "label": "Schedule of Beneficiaries",
        "issuing_authority": "Trustees",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 306,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Schedule of trust beneficiaries. Names, ID numbers, class (income/capital/discretionary).",
        "extraction_schema": {
            "trust_name":             {"type": "string", "label": "Trust Name",                "required": True},
            "beneficiaries":          {"type": "list",   "label": "Beneficiaries",             "required": True},
            "classes_of_beneficiaries":{"type": "string","label": "Classes of Beneficiaries",  "required": False},
            "date_updated":           {"type": "date",   "label": "Date Updated",              "required": False},
        },
    },
    {
        "code": "trustee_undertaking",
        "label": "Trustee Acceptance / Undertaking",
        "issuing_authority": "Trustee",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act s.6",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 307,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Signed trustee acceptance of appointment. Trustee name, trust name, date, witness signatures.",
        "extraction_schema": {
            "trustee_name": {"type": "string", "label": "Trustee Name", "required": True},
            "trust_name":   {"type": "string", "label": "Trust Name",   "required": True},
            "date_signed":  {"type": "date",   "label": "Date Signed",  "required": True},
        },
    },
    {
        "code": "trust_amendment_deed",
        "label": "Amendment to Trust Deed",
        "issuing_authority": "Founder / Trustees / Court",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 308,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Amendment or addendum to original trust deed. References original trust deed date. May require Master approval.",
        "extraction_schema": {
            "trust_name":            {"type": "string", "label": "Trust Name",             "required": True},
            "trust_number":          {"type": "string", "label": "IT Number",              "required": False},
            "amendment_description": {"type": "text",   "label": "Amendment Description",  "required": False},
            "effective_date":        {"type": "date",   "label": "Effective Date",         "required": False},
        },
    },
    {
        "code": "trust_investment_mandate",
        "label": "Investment Policy / Mandate (Trust)",
        "issuing_authority": "Trustees",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 309,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Trust investment policy statement or mandate. Asset allocation, risk profile, benchmarks, restrictions.",
        "extraction_schema": {
            "trust_name":     {"type": "string", "label": "Trust Name",      "required": True},
            "asset_allocation":{"type": "dict",  "label": "Asset Allocation", "required": False},
            "risk_profile":   {"type": "string", "label": "Risk Profile",    "required": False},
            "date_approved":  {"type": "date",   "label": "Date Approved",   "required": False},
        },
    },
    {
        "code": "trust_financial_statements",
        "label": "Trust Financial Statements",
        "issuing_authority": "Accountant / Auditor",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 310,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Annual financial statements for a trust. Trust name and IT number. Balance sheet, income statement.",
        "extraction_schema": {
            "trust_name":       {"type": "string",  "label": "Trust Name",       "required": True},
            "financial_year":   {"type": "string",  "label": "Financial Year",   "required": True},
            "total_assets":     {"type": "decimal", "label": "Total Assets",     "required": False},
            "total_liabilities":{"type": "decimal", "label": "Total Liabilities","required": False},
            "income":           {"type": "decimal", "label": "Income",           "required": False},
            "expenses":         {"type": "decimal", "label": "Expenses",         "required": False},
        },
    },
    {
        "code": "master_correspondence",
        "label": "Master of the High Court Correspondence",
        "issuing_authority": "Master of the High Court",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 311,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Letter or notice from Master of the High Court. References trust IT number. Master's stamp/letterhead.",
        "extraction_schema": {
            "trust_name":   {"type": "string", "label": "Trust Name",      "required": True},
            "trust_number": {"type": "string", "label": "IT Number",       "required": False},
            "reference":    {"type": "string", "label": "Reference Number","required": False},
            "subject":      {"type": "string", "label": "Subject",         "required": False},
            "date":         {"type": "date",   "label": "Date",            "required": False},
        },
    },
    {
        "code": "trust_minutes",
        "label": "Minutes of Trustees' Meeting",
        "issuing_authority": "Trustees",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Trust Property Control Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["trust"],
        "sort_order": 312,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Minutes of a trustees meeting. Trust name, date, attendees, agenda items, resolutions passed.",
        "extraction_schema": {
            "trust_name":  {"type": "string", "label": "Trust Name",           "required": True},
            "date":        {"type": "date",   "label": "Meeting Date",         "required": True},
            "attendees":   {"type": "list",   "label": "Attendees",            "required": False},
            "resolutions": {"type": "list",   "label": "Resolutions Passed",   "required": False},
        },
    },

    # ── Close Corporation (sort_order 400-408) ────────────────────────────────
    {
        "code": "ck1_registration",
        "label": "CK1 CC Registration Certificate",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": True,
        "regulatory_reference": "Close Corporations Act s.12",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 400,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": ["CK1"],
        "is_active": True,
        "classification_signals": "CK1 Close Corporation registration certificate. CC registration number format YYYY/NNNNNN/23. Lists members and interest percentages.",
        "extraction_schema": {
            "cc_name":             {"type": "string", "label": "CC Name",             "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "registration_date":   {"type": "date",   "label": "Registration Date",   "required": True},
            "members":             {"type": "list",   "label": "Members",             "required": False},
        },
    },
    {
        "code": "ck2_amendment",
        "label": "CK2 CC Amendment",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act s.15",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 401,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": ["CK2"],
        "is_active": True,
        "classification_signals": "CK2 form for CC amendments — member changes, name changes, address changes. References original CK1.",
        "extraction_schema": {
            "cc_name":             {"type": "string", "label": "CC Name",             "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "amendment_type":      {"type": "string", "label": "Amendment Type",      "required": False},
            "effective_date":      {"type": "date",   "label": "Effective Date",      "required": False},
        },
    },
    {
        "code": "cc_founding_statement",
        "label": "CC Founding Statement",
        "issuing_authority": "Members",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act s.12",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 402,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Founding statement of a Close Corporation. Members, member interest percentages, principal business.",
        "extraction_schema": {
            "cc_name":            {"type": "string", "label": "CC Name",             "required": True},
            "members":            {"type": "list",   "label": "Members",             "required": True},
            "member_interest_pct":{"type": "dict",   "label": "Member Interest %",   "required": False},
            "principal_business": {"type": "string", "label": "Principal Business",  "required": False},
        },
    },
    {
        "code": "cc_association_agreement",
        "label": "CC Association Agreement",
        "issuing_authority": "Members",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act s.44",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 403,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Association agreement between CC members. Governs profit sharing, management, decision making.",
        "extraction_schema": {
            "cc_name":         {"type": "string", "label": "CC Name",          "required": True},
            "parties":         {"type": "list",   "label": "Parties",          "required": True},
            "profit_sharing":  {"type": "dict",   "label": "Profit Sharing",   "required": False},
            "management_rights":{"type": "text",  "label": "Management Rights","required": False},
        },
    },
    {
        "code": "cc_annual_return",
        "label": "CC Annual Return",
        "issuing_authority": "CIPC",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act s.15",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 404,
        "email_sender_patterns": ["*@cipc.co.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "CIPC annual return confirmation for Close Corporation. CC registration number, filing date, compliance status.",
        "extraction_schema": {
            "cc_name":             {"type": "string", "label": "CC Name",             "required": True},
            "registration_number": {"type": "string", "label": "Registration Number", "required": True},
            "financial_year_end":  {"type": "string", "label": "Financial Year End",  "required": False},
            "filing_date":         {"type": "date",   "label": "Filing Date",         "required": False},
        },
    },
    {
        "code": "cc_tax_clearance",
        "label": "Tax Clearance Certificate (CC)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Tax Administration Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 405,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS tax clearance for Close Corporation. CC tax number, valid period, compliance status.",
        "extraction_schema": {
            "cc_name":    {"type": "string", "label": "CC Name",           "required": True},
            "tax_number": {"type": "string", "label": "Tax Number",        "required": True},
            "valid_from": {"type": "date",   "label": "Valid From",        "required": True},
            "valid_to":   {"type": "date",   "label": "Valid To",          "required": True},
            "status":     {"type": "string", "label": "Compliance Status", "required": True},
        },
    },
    {
        "code": "cc_bank_confirmation",
        "label": "Bank Confirmation Letter (CC)",
        "issuing_authority": "Bank",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 406,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Bank letterhead confirming CC account details. CC name, account number, branch code.",
        "extraction_schema": {
            "cc_name":        {"type": "string", "label": "CC Name",        "required": True},
            "bank_name":      {"type": "string", "label": "Bank Name",      "required": True},
            "account_number": {"type": "string", "label": "Account Number", "required": True},
            "branch_code":    {"type": "string", "label": "Branch Code",    "required": True},
            "date_issued":    {"type": "date",   "label": "Date Issued",    "required": True},
        },
    },
    {
        "code": "cc_member_resolution",
        "label": "Members' Resolution (CC)",
        "issuing_authority": "Members",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 407,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "CC members resolution. Headed 'Resolution of Members'. CC registration number. Signatures of all members.",
        "extraction_schema": {
            "cc_name":           {"type": "string", "label": "CC Name",            "required": True},
            "resolution_subject":{"type": "string", "label": "Resolution Subject", "required": False},
            "date_passed":       {"type": "date",   "label": "Date Passed",        "required": True},
            "members_present":   {"type": "list",   "label": "Members Present",    "required": False},
        },
    },
    {
        "code": "cc_financial_statements",
        "label": "CC Financial Statements",
        "issuing_authority": "Accountant",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Close Corporations Act s.58",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["close_corporation"],
        "sort_order": 408,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Annual financial statements for CC. Balance sheet, income statement, signed by member and accountant.",
        "extraction_schema": {
            "cc_name":        {"type": "string",  "label": "CC Name",          "required": True},
            "financial_year": {"type": "string",  "label": "Financial Year",   "required": True},
            "total_assets":   {"type": "decimal", "label": "Total Assets",     "required": False},
            "total_liabilities":{"type": "decimal","label": "Total Liabilities","required": False},
            "income":         {"type": "decimal", "label": "Income",           "required": False},
        },
    },

    # ── Sole Proprietary (sort_order 500-508) ─────────────────────────────────
    {
        "code": "sole_prop_id",
        "label": "Owner ID Document (Sole Prop)",
        "issuing_authority": "DHA",
        "is_primary_identity_doc": True,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 500,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SA ID or passport of sole proprietor. Required for FICA identification of the business owner.",
        "extraction_schema": {
            "owner_name":   {"type": "string", "label": "Owner Name",   "required": True},
            "id_number":    {"type": "string", "label": "ID Number",    "required": True},
            "date_of_birth":{"type": "date",   "label": "Date of Birth","required": False},
        },
    },
    {
        "code": "sole_prop_trade_licence",
        "label": "Trading Licence / Business Permit",
        "issuing_authority": "Municipality",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Businesses Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 501,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Municipal trading licence or business permit. Trade name, owner name, licence number, business type, valid period.",
        "extraction_schema": {
            "trade_name":    {"type": "string", "label": "Trade Name",    "required": True},
            "owner_name":    {"type": "string", "label": "Owner Name",    "required": True},
            "licence_number":{"type": "string", "label": "Licence Number","required": False},
            "valid_to":      {"type": "date",   "label": "Valid To",      "required": False},
            "business_type": {"type": "string", "label": "Business Type", "required": False},
        },
    },
    {
        "code": "sole_prop_tax_registration",
        "label": "SARS Tax Registration (Sole Prop)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Tax Administration Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 502,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS income tax registration confirmation. Owner name, tax reference number, registration date.",
        "extraction_schema": {
            "owner_name":        {"type": "string", "label": "Owner Name",        "required": True},
            "tax_number":        {"type": "string", "label": "Tax Number",        "required": True},
            "registration_date": {"type": "date",   "label": "Registration Date", "required": False},
        },
    },
    {
        "code": "sole_prop_vat_cert",
        "label": "VAT Certificate (Sole Prop)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "VAT Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 503,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS VAT registration certificate for sole proprietor. Trade name, VAT number starting with 4.",
        "extraction_schema": {
            "trade_name":        {"type": "string", "label": "Trade Name",        "required": True},
            "vat_number":        {"type": "string", "label": "VAT Number",        "required": True},
            "registration_date": {"type": "date",   "label": "Registration Date", "required": False},
        },
    },
    {
        "code": "sole_prop_bank_confirmation",
        "label": "Bank Confirmation Letter (Sole Prop)",
        "issuing_authority": "Bank",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 504,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Bank letterhead confirming sole proprietor or trading account. Trade name or owner name, account number, branch code.",
        "extraction_schema": {
            "trade_name":     {"type": "string", "label": "Trade / Owner Name", "required": True},
            "bank_name":      {"type": "string", "label": "Bank Name",          "required": True},
            "account_number": {"type": "string", "label": "Account Number",     "required": True},
            "branch_code":    {"type": "string", "label": "Branch Code",        "required": True},
            "date_issued":    {"type": "date",   "label": "Date Issued",        "required": True},
        },
    },
    {
        "code": "sole_prop_tax_clearance",
        "label": "Tax Clearance Certificate (Sole Prop)",
        "issuing_authority": "SARS",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Tax Administration Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 505,
        "email_sender_patterns": ["*@sars.gov.za"],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "SARS tax clearance for sole proprietor. Owner name, tax number, valid period, compliance status.",
        "extraction_schema": {
            "owner_name": {"type": "string", "label": "Owner Name",  "required": True},
            "tax_number": {"type": "string", "label": "Tax Number",  "required": True},
            "valid_from": {"type": "date",   "label": "Valid From",  "required": True},
            "valid_to":   {"type": "date",   "label": "Valid To",    "required": True},
        },
    },
    {
        "code": "sole_prop_proof_of_address",
        "label": "Business Proof of Address (Sole Prop)",
        "issuing_authority": "Various",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FICA s.21",
        "default_validity_days": 90,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 506,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Utility bill or bank statement showing business address. Trade name or owner name, dated within 3 months.",
        "extraction_schema": {
            "trade_name":       {"type": "string", "label": "Trade / Owner Name", "required": True},
            "business_address": {"type": "text",   "label": "Business Address",   "required": True},
            "date_issued":      {"type": "date",   "label": "Date Issued",        "required": True},
        },
    },
    {
        "code": "sole_prop_fic_registration",
        "label": "FIC Registration (Sole Prop)",
        "issuing_authority": "Financial Intelligence Centre",
        "is_primary_identity_doc": False,
        "regulatory_reference": "FIC Act",
        "default_validity_days": None,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 507,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "FIC registration confirmation for sole proprietor operating as accountable or reporting institution.",
        "extraction_schema": {
            "trade_name":        {"type": "string", "label": "Trade Name",          "required": True},
            "fic_reference":     {"type": "string", "label": "FIC Reference Number","required": True},
            "registration_date": {"type": "date",   "label": "Registration Date",   "required": False},
        },
    },
    {
        "code": "sole_prop_financial_statements",
        "label": "Financial Statements (Sole Prop)",
        "issuing_authority": "Accountant",
        "is_primary_identity_doc": False,
        "regulatory_reference": "Income Tax Act",
        "default_validity_days": 365,
        "ownership_scope": "owner_bound",
        "applies_to_entity_types": ["sole_proprietary"],
        "sort_order": 508,
        "email_sender_patterns": [],
        "email_subject_patterns": [],
        "external_reference_codes": [],
        "is_active": True,
        "classification_signals": "Annual financial statements or management accounts for sole proprietor. Owner name, trade name, financial year, income and expenses.",
        "extraction_schema": {
            "trade_name":     {"type": "string",  "label": "Trade Name",     "required": True},
            "financial_year": {"type": "string",  "label": "Financial Year", "required": True},
            "gross_income":   {"type": "decimal", "label": "Gross Income",   "required": False},
            "expenses":       {"type": "decimal", "label": "Expenses",       "required": False},
            "net_income":     {"type": "decimal", "label": "Net Income",     "required": False},
        },
    },
]


def seed_forward(apps, schema_editor):
    Catalogue = apps.get_model("the_volt", "DocumentTypeCatalogue")
    for doc in DOCUMENTS:
        doc_copy = doc.copy()
        code = doc_copy.pop("code")
        Catalogue.objects.update_or_create(code=code, defaults=doc_copy)


def seed_reverse(apps, schema_editor):
    Catalogue = apps.get_model("the_volt", "DocumentTypeCatalogue")
    codes = [d["code"] for d in DOCUMENTS]
    Catalogue.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):
    dependencies = [("the_volt", "0008_merge_20260416_0125")]
    operations = [migrations.RunPython(seed_forward, seed_reverse)]
