# Generated by Django 5.2.12 on 2026-03-25 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0009_ensure_agentquestion_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI Assistant', max_length=200)),
                ('maintenance_report_suggested', models.BooleanField(default=False, help_text='True once this chat has identified a maintenance issue (show structured report CTA).')),
                ('messages', models.JSONField(default=list, help_text='Ordered list of {"id", "role", "content", "created_at", "attachment_kind", "attachment_storage"?}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_question', models.ForeignKey(blank=True, help_text='Optional link to an open agent question tied to this thread.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_chat_sessions', to='maintenance.agentquestion')),
                ('maintenance_request', models.ForeignKey(blank=True, help_text='Set when a maintenance request is created from this chat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_chat_sessions', to='maintenance.maintenancerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
