# Generated by Django 5.2.12 on 2026-03-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_migrate_legacy_tenant_chats'),
        ('properties', '0003_unitinfo_propertyagentconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(default=dict, help_text='Key-value pairs extracted from chats: contact_preference, known_issues, notes, etc.')),
                ('question_categories', models.JSONField(default=dict, help_text='Category → count, e.g. {"maintenance_ticket": 4, "general_enquiry": 12}')),
                ('total_chats', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('complaint_score', models.FloatField(default=0.0, help_text='0-1 ratio of complaint/maintenance chats to total chats.')),
                ('last_chat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_intel_profiles', to='properties.property')),
                ('unit_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_intel_profiles', to='properties.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_intel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tenant intelligence profiles',
            },
        ),
    ]
