# Generated by Django 5.2.12 on 2026-04-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_tenantintelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('agent', 'Agent'), ('owner', 'Owner'), ('supplier', 'Supplier')], default='agent', max_length=20)),
                ('message', models.TextField(help_text='Raw user message sent to the guide.')),
                ('intent', models.CharField(blank=True, default='', help_text='Tool name resolved by the AI (blank if no tool was called).', max_length=80)),
                ('action_taken', models.JSONField(default=dict, help_text='GuideAction payload returned to the frontend (empty dict if none).')),
                ('completed', models.BooleanField(default=False, help_text='True when the guide resolved a navigation action.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
