# Generated by Django 5.2.12 on 2026-05-06 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('ai', '0004_add_guide_interaction'),
        ('maintenance', '0018_backfill_agency_id_maintenance'),
        ('properties', '0031_backfill_agency_id_remaining_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guideinteraction',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guide_interactions', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='guideinteraction',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Klikk processes guide messages on agency instruction (s21).', max_length=32),
        ),
        migrations.AddField(
            model_name='guideinteraction',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='ai_chat_90d', help_text='POPIA s14 retention. Guide interactions purge after 90 days.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantchatsession',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_chat_sessions', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='tenantchatsession',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. AI processing on agency instruction (s21).', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantchatsession',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='ai_chat_90d', help_text='POPIA s14 retention. AI chat — 90 days unless retained.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantintelligence',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_intel_profiles', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='tenantintelligence',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Profile derived under operator instruction (s21).', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantintelligence',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='ai_chat_90d', help_text='POPIA s14 retention. Tracks chat-derived facts; aligns with chat ttl.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='guideinteraction',
            index=models.Index(fields=['agency', 'created_at'], name='guide_int_agency_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantchatsession',
            index=models.Index(fields=['agency', 'updated_at'], name='tenant_chat_agency_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantintelligence',
            index=models.Index(fields=['agency', 'updated_at'], name='tenant_intel_agency_ts_idx'),
        ),
    ]
