# Generated by Django 5.2.13 on 2026-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_seed_genesis_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_content_f9ce81_idx',
            old_name='audit_audte_content_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_d7f04a_idx',
            old_name='audit_audte_action_idx',
        ),
    ]
