# Generated by Django 5.2.12 on 2026-05-06 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('audit', '0003_rename_audit_audte_content_idx_audit_audit_content_f9ce81_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from actor.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Audit trails = legal obligation (FICA / EAAB).', max_length=32),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Audit trail permanent — references anonymised.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['agency', 'timestamp'], name='audit_event_agency_ts_idx'),
        ),
    ]
