# Generated by Django 5.2.12 on 2026-04-12 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_add_monthly_income_to_person'),
        ('leases', '0016_add_barcode_to_inventory'),
        ('properties', '0019_add_photo_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this tenant currently active in the system?')),
                ('notes', models.TextField(blank=True, help_text='Agent notes about this tenant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, help_text='Portal login account (optional — not all tenants have portal access). Link this once the tenant has been invited and accepted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_records', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(help_text='Legal identity — must already exist as a Person record.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='accounts.person')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['person__full_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantUnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Inclusive start of occupancy.')),
                ('end_date', models.DateField(blank=True, help_text='Inclusive end of occupancy. Leave blank for open-ended (current).', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('lease', 'From Lease')], default='manual', help_text='How this assignment was created.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional context for this assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Agent or admin who created this assignment. Null for lease-derived assignments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, help_text='Set when this assignment was derived from a specific lease.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_assignment', to='leases.lease')),
                ('property', models.ForeignKey(help_text='Denormalized from unit.property at assignment time. Do not edit directly.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_assignments', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenant.tenant')),
                ('unit', models.ForeignKey(help_text='The unit occupied. Cannot be deleted while assignments exist.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_assignments', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Unit Assignment',
                'verbose_name_plural': 'Unit Assignments',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'start_date'], name='tenant_assign_tenant_date_idx'), models.Index(fields=['unit', 'start_date'], name='tenant_assign_unit_date_idx')],
            },
        ),
    ]
