# Generated by Django 5.2.12 on 2026-05-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_backfill_agency_id_accounts'),
        ('leases', '0025_backfill_agency_id_leases'),
        ('properties', '0031_backfill_agency_id_remaining_properties'),
        ('tenant', '0002_tenant_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from person.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Tenant record = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Tenant kept for lease lifetime + obligations.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_onboardings', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Tenant onboarding = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Onboarding artefacts kept for lease lifetime.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantunitassignment',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from property.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_unit_assignments', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='tenantunitassignment',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Occupancy record = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenantunitassignment',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Kept for lease lifetime + obligations.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['agency', 'is_active'], name='tenant_agency_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantonboarding',
            index=models.Index(fields=['agency', 'completed_at'], name='tenonb_agency_done_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantunitassignment',
            index=models.Index(fields=['agency', 'start_date'], name='tenant_assign_agency_date_idx'),
        ),
    ]
