# Generated by Django 5.2.12 on 2026-03-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact person name', max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_radius_km', models.PositiveIntegerField(blank=True, help_text='How far this supplier is willing to travel (km)', null=True)),
                ('bee_level', models.CharField(blank=True, help_text='e.g. Level 1', max_length=10)),
                ('cidb_grading', models.CharField(blank=True, help_text='e.g. 3CE', max_length=20)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('insurance_details', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('account_type', models.CharField(blank=True, help_text='savings / cheque', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='1.0–5.0 average rating', max_digits=2, null=True)),
                ('ai_profile', models.JSONField(blank=True, help_text='AI-enriched profile: specialities, past job summaries, strengths, availability patterns', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='maintenance.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('hvac', 'HVAC'), ('locksmith', 'Locksmith'), ('pest_control', 'Pest Control'), ('landscaping', 'Landscaping'), ('appliance', 'Appliance Repair'), ('general', 'General Maintenance'), ('security', 'Security'), ('cleaning', 'Cleaning'), ('other', 'Other')], max_length=30)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='maintenance.supplier')),
            ],
            options={
                'ordering': ['trade'],
                'unique_together': {('supplier', 'trade')},
            },
        ),
    ]
