# Generated by Django 5.2.12 on 2026-03-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_supplier_maintenancerequest_supplier_suppliertrade'),
        ('properties', '0002_property_owner_alter_property_agent_propertygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ai_profile',
            field=models.JSONField(blank=True, help_text='AI-enriched profile for smart supplier-job matching', null=True),
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bank_confirmation', 'Bank Confirmation'), ('bee_certificate', 'BEE Certificate'), ('insurance', 'Insurance Certificate'), ('cidb', 'CIDB Registration'), ('company_reg', 'Company Registration'), ('tax_clearance', 'Tax Clearance'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='supplier_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='maintenance.supplier')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='properties.property')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='maintenance.supplier')),
            ],
            options={
                'ordering': ['property__name'],
                'unique_together': {('supplier', 'property')},
            },
        ),
    ]
