# Generated by Django 5.2.12 on 2026-03-24 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_supplier_website_alter_supplier_ai_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('quoting', 'Quoting'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes sent to suppliers with the job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('quoted', 'Quoted'), ('declined', 'Declined'), ('awarded', 'Awarded'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_reasons', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='maintenance.jobdispatch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='maintenance.supplier')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('dispatch', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='JobQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Scope of work / notes')),
                ('estimated_days', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='maintenance.jobquoterequest')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
