# Generated by Django 5.2.12 on 2026-03-24 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_jobdispatch_jobquoterequest_jobquote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text='System login account for supplier portal access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
