# Generated by Django 5.2.12 on 2026-03-25 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenanceskill'),
        ('properties', '0003_unitinfo_propertyagentconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question the AI agent needs answered')),
                ('answer', models.TextField(blank=True, help_text='Human-provided answer')),
                ('category', models.CharField(choices=[('property', 'Property Info'), ('lease', 'Lease / Contract'), ('maintenance', 'Maintenance'), ('tenant', 'Tenant'), ('supplier', 'Supplier'), ('policy', 'Policy / Rules'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('context_source', models.CharField(blank=True, help_text='What triggered this question, e.g. maintenance request #123', max_length=200)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('added_to_context', models.BooleanField(default=False, help_text='Whether the answer was synced to agent knowledge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_questions', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('status_change', 'Status Change'), ('supplier_assigned', 'Supplier Assigned'), ('dispatch_sent', 'Dispatch Sent'), ('quote_received', 'Quote Received'), ('job_awarded', 'Job Awarded'), ('system', 'System')], default='note', max_length=30)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_activities', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='maintenance.maintenancerequest')),
            ],
            options={
                'db_table': 'maintenance_maintenanceactivity',
                'ordering': ['created_at'],
            },
        ),
    ]
