# Generated by Django 5.2.12 on 2026-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_ensure_agentquestion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roof', 'Roof / Ceiling'), ('appliance', 'Appliance'), ('security', 'Security'), ('pest', 'Pest Control'), ('garden', 'Garden / Exterior'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
