# Generated by Django 5.2.12 on 2026-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_sync_db_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceactivity',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/activity_files/'),
        ),
        migrations.AlterField(
            model_name='maintenanceactivity',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenanceactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
