# Generated by Django 5.2.12 on 2026-04-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_subscription_tier'),
        ('maintenance', '0014_supplierjobassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='sla_ack_deadline',
            field=models.DateTimeField(blank=True, help_text='Computed: created_at + ack SLA hours for this priority', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='sla_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='sla_resolve_deadline',
            field=models.DateTimeField(blank=True, help_text='Computed: created_at + resolve SLA hours for this priority', null=True),
        ),
        migrations.CreateModel(
            name='AgencySLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent (emergency)'), ('high', 'High (urgent)'), ('medium', 'Medium (routine)'), ('low', 'Low (routine)')], max_length=10)),
                ('ack_hours', models.PositiveIntegerField(help_text='Hours to first acknowledgement')),
                ('resolve_hours', models.PositiveIntegerField(help_text='Hours to full resolution')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_configs', to='accounts.agency')),
            ],
            options={
                'ordering': ['agency', 'priority'],
                'unique_together': {('agency', 'priority')},
            },
        ),
    ]
