# Generated by Django 5.2.12 on 2026-05-06 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('maintenance', '0016_supplier_invoice'),
        ('properties', '0031_backfill_agency_id_remaining_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyslaconfig',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. SLA config is operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='agencyslaconfig',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Config rows: no automated retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='agentquestion',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from property.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_questions', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='agentquestion',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='agentquestion',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='agenttokenlog',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency when present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_token_logs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='agenttokenlog',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Token usage logging = operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='agenttokenlog',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='ai_chat_90d', help_text='POPIA s14 retention. AI chat logs: 90 days.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobdispatch',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from maintenance_request.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_dispatches', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='jobdispatch',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobdispatch',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobquote',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from quote_request.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_quotes', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='jobquote',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobquote',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobquoterequest',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from dispatch.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_quote_requests', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='jobquoterequest',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='jobquoterequest',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from request.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_activities', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceactivity',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Denormalised from unit.property.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Maintenance under lease = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceskill',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency. Null = platform-global skill library entry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_skills', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='maintenanceskill',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Skills library is operator-instruction; no PI.', max_length=32),
        ),
        migrations.AddField(
            model_name='maintenanceskill',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Library entries: no automated retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Suppliers never cross agencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='anonymisation_reason',
            field=models.CharField(blank=True, choices=[('dsar_deletion', 'Subject requested deletion (s24)'), ('retention_expired', 'Retention window expired (s14)'), ('agency_offboarding', 'Agency closed account / cancelled subscription'), ('data_quality', 'Record corrected — superseded data anonymised'), ('operator_decision', 'Klikk operator decision (rare)')], default='', help_text='Why this record was anonymised (POPIA s23/s24 audit trail).', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_anonymised',
            field=models.BooleanField(default=False, help_text='True after PII fields have been scrubbed per a DSAR or retention policy.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Supplier = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention. Default 5 years (FICA s42/s43).', max_length=32),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vault_entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Vault33 VaultEntity PK once supplier identity is mirrored.', null=True),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from supplier.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. FICA documents = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention obligation. FICA s42/s43 5-year minimum.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from quote_request.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention. Financial records: FICA s42/s43 5-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierjobassignment',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from maintenance_request.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_job_assignments', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supplierjobassignment',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierjobassignment',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention. RHA dispute-records 3-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierproperty',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_property_links', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='supplierproperty',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierproperty',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='suppliertrade',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from supplier.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_trades', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='suppliertrade',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='suppliertrade',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention obligation.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='agentquestion',
            index=models.Index(fields=['agency', 'status'], name='aq_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttokenlog',
            index=models.Index(fields=['agency', 'endpoint'], name='tlog_agency_endpoint_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdispatch',
            index=models.Index(fields=['agency', 'status'], name='dispatch_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobquote',
            index=models.Index(fields=['agency', 'amount'], name='quote_agency_amount_idx'),
        ),
        migrations.AddIndex(
            model_name='jobquoterequest',
            index=models.Index(fields=['agency', 'status'], name='qreq_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceactivity',
            index=models.Index(fields=['agency', 'activity_type'], name='mact_agency_type_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['agency', 'status'], name='mreq_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['agency', '-created_at'], name='mreq_agency_created_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceskill',
            index=models.Index(fields=['agency', 'trade'], name='mskill_agency_trade_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['agency', 'name'], name='supplier_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['vault_entity_id'], name='supplier_vault_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierdocument',
            index=models.Index(fields=['agency', 'document_type'], name='supdoc_agency_type_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['agency', 'status'], name='sinv_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierjobassignment',
            index=models.Index(fields=['agency', 'status'], name='sja_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierproperty',
            index=models.Index(fields=['agency', 'is_preferred'], name='supprop_agency_pref_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliertrade',
            index=models.Index(fields=['agency', 'trade'], name='suptrade_agency_trade_idx'),
        ),
    ]
