# Generated by Django 5.2.12 on 2026-03-24 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Person or company that owns this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.ManyToManyField(blank=True, related_name='groups', to='properties.property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
