# Generated by Django 5.2.12 on 2026-03-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_unitinfo_propertyagentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(help_text='Company or individual name', max_length=200)),
                ('owner_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('trust', 'Trust')], default='company', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('owner_address', models.JSONField(blank=True, default=dict, help_text='street, city, province, postal_code')),
                ('representative_name', models.CharField(blank=True, max_length=200)),
                ('representative_id_number', models.CharField(blank=True, max_length=20)),
                ('representative_email', models.EmailField(blank=True, max_length=254)),
                ('representative_phone', models.CharField(blank=True, max_length=20)),
                ('bank_details', models.JSONField(blank=True, default=dict, help_text='bank_name, branch_code, account_number, account_type, account_holder')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = current owner', null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property')),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
