# Generated by Django 5.2.12 on 2026-04-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_person_address_person_date_of_birth_and_more'),
        ('properties', '0004_propertyownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal name of landlord/company/trust', max_length=200)),
                ('landlord_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('trust', 'Trust')], default='individual', max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='SA ID or passport', max_length=20)),
                ('registration_number', models.CharField(blank=True, help_text='Company/trust reg number', max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.JSONField(blank=True, default=dict, help_text='street, city, province, postal_code')),
                ('representative_name', models.CharField(blank=True, max_length=200)),
                ('representative_id_number', models.CharField(blank=True, max_length=20)),
                ('representative_email', models.EmailField(blank=True, max_length=254)),
                ('representative_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(blank=True, help_text='Link to Person record for shared identity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_profile', to='accounts.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'Main rental account'", max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_type', models.CharField(blank=True, help_text='e.g. Cheque, Savings, Transmission', max_length=30)),
                ('account_holder', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='properties.landlord')),
            ],
            options={
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownerships', to='properties.landlord'),
        ),
    ]
