# Generated by Django 5.2.12 on 2026-04-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_landlord_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(choices=[('electrical', 'Electrical CoC'), ('pest', 'Pest (Woodborer) Clearance'), ('gas', 'Gas CoC'), ('plumbing', 'Plumbing CoC'), ('fence', 'Electric Fence CoC'), ('solar', 'Solar Installation CoC'), ('other', 'Other')], max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no fixed expiry (e.g. pest clearance)', null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_phone', models.CharField(blank=True, max_length=30)),
                ('contractor_email', models.EmailField(blank=True, max_length=254)),
                ('registration_number', models.CharField(blank=True, help_text="Contractor's DoL/DoE registration number", max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='properties/compliance/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certs', to='properties.property')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('rates', 'Property Rates'), ('water', 'Water'), ('electricity', 'Electricity'), ('refuse', 'Refuse'), ('sewerage', 'Sewerage'), ('combined', 'Combined Municipal Account')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Payment reference e.g. ERF 3587 STELL CLR', max_length=100)),
                ('meter_number', models.CharField(blank=True, max_length=50)),
                ('in_tenant_name', models.BooleanField(default=False, help_text='True if currently billed to tenant')),
                ('monthly_levy', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly charge', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_accounts', to='properties.property')),
            ],
            options={
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erf_number', models.CharField(blank=True, help_text='e.g. ERF 3587', max_length=30)),
                ('title_deed_number', models.CharField(blank=True, max_length=50)),
                ('municipality', models.CharField(blank=True, help_text='e.g. Stellenbosch Municipality', max_length=100)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('zoning', models.CharField(blank=True, help_text='e.g. Residential 1', max_length=100)),
                ('erf_size_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Stand/erf area m²', max_digits=10, null=True)),
                ('floor_size_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Gross livable area m²', max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('construction_type', models.CharField(blank=True, choices=[('face_brick', 'Face Brick'), ('plaster', 'Plastered Brick'), ('timber_frame', 'Timber Frame'), ('steel_frame', 'Steel Frame'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=20)),
                ('roof_type', models.CharField(blank=True, choices=[('cement_tile', 'Cement Tile'), ('clay_tile', 'Clay Tile'), ('ibr', 'IBR Sheeting'), ('thatch', 'Thatch'), ('flat', 'Flat Roof'), ('other', 'Other')], max_length=20)),
                ('number_of_storeys', models.PositiveSmallIntegerField(default=1)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_flatlet', models.BooleanField(default=False, help_text='Self-contained secondary unit on the erf')),
                ('garden_type', models.CharField(blank=True, help_text='e.g. Established garden, low maintenance', max_length=100)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('municipal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Council valuation roll value', max_digits=14, null=True)),
                ('municipal_value_date', models.DateField(blank=True, null=True)),
                ('drive_photos_url', models.URLField(blank=True, help_text='Google Drive folder — property photos', max_length=500)),
                ('drive_documents_url', models.URLField(blank=True, help_text='Google Drive folder — all documents', max_length=500)),
                ('drive_plans_url', models.URLField(blank=True, help_text='Google Drive folder — house plans', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='properties/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('flatlet', 'Flatlet'), ('garden', 'Garden'), ('plans', 'Floor Plans'), ('other', 'Other')], default='exterior', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order — 0 = cover photo')),
                ('is_cover', models.BooleanField(default=False)),
                ('drive_url', models.URLField(blank=True, help_text='Original Google Drive URL if synced from Drive', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, help_text='Leave blank for property-level photos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='properties.unit')),
            ],
            options={
                'ordering': ['position', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_type', models.CharField(choices=[('purchase', 'Purchase Price'), ('municipal', 'Municipal Valuation'), ('bank', 'Bank Valuation'), ('agent', 'Agent Estimate'), ('formal', 'Formal Appraisal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valuation_date', models.DateField()),
                ('valuator', models.CharField(blank=True, help_text='Bank, agent, or firm name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property')),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
    ]
