# Generated by Django 5.2.12 on 2026-04-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_compliancecertificate_municipalaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('building', 'Building / Structure'), ('contents', 'Contents'), ('combined', 'Building + Contents'), ('liability', 'Public Liability'), ('landlord', 'Landlord Insurance'), ('other', 'Other')], max_length=20)),
                ('insurer', models.CharField(help_text='e.g. Outsurance, Santam, Momentum', max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('broker', models.CharField(blank=True, max_length=200)),
                ('broker_email', models.EmailField(blank=True, max_length=254)),
                ('broker_phone', models.CharField(blank=True, max_length=30)),
                ('sum_insured', models.DecimalField(blank=True, decimal_places=2, help_text='Replacement value insured', max_digits=14, null=True)),
                ('monthly_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('excess', models.DecimalField(blank=True, decimal_places=2, help_text='Standard excess per claim', max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = ongoing', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='properties/insurance/policies/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='properties.property')),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('storm', 'Storm / Wind / Hail'), ('fire', 'Fire'), ('flood', 'Flood / Water Damage'), ('theft', 'Theft / Burglary'), ('geyser', 'Geyser Burst'), ('subsidence', 'Subsidence / Settling'), ('liability', 'Third-Party Liability'), ('other', 'Other')], max_length=20)),
                ('claim_number', models.CharField(blank=True, help_text="Insurer's claim reference number", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft / Not Yet Submitted'), ('submitted', 'Submitted'), ('assessing', 'Under Assessment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled / Paid Out'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('incident_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('claimed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('excess_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount actually paid by insurer', max_digits=12, null=True)),
                ('description', models.TextField(help_text='What happened — used for claim submission and RAG context')),
                ('document', models.FileField(blank=True, help_text='Claim form or insurer correspondence', null=True, upload_to='properties/insurance/claims/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='properties.unit')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='properties.insurancepolicy')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='MunicipalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text='Copied from account if blank', max_length=50)),
                ('billing_month', models.PositiveSmallIntegerField(help_text='1–12')),
                ('billing_year', models.PositiveSmallIntegerField()),
                ('rates_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refuse_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sewerage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partially Paid'), ('dispute', 'In Dispute')], default='unpaid', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, help_text='Scanned/downloaded bill PDF', null=True, upload_to='properties/municipal_bills/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='properties.municipalaccount')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipal_bills', to='properties.property')),
            ],
            options={
                'ordering': ['-billing_year', '-billing_month'],
                'unique_together': {('property', 'municipal_account', 'billing_year', 'billing_month')},
            },
        ),
    ]
