# Generated by Django 5.2.12 on 2026-04-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_insurancepolicy_insuranceclaim_municipalbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ad_description',
            field=models.TextField(blank=True, help_text='Advertising copy used in rental listings'),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor_size_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='toilets',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
