# Generated by Django 5.2.12 on 2026-04-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_add_unit_ad_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.TextField(blank=True, help_text='House rules shown to tenants — parking, noise, pets, visitors, etc.'),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='properties/documents/')),
                ('doc_type', models.CharField(choices=[('house_rules', 'House Rules'), ('body_corporate', 'Body Corporate / HOA'), ('title_deed', 'Title Deed'), ('floor_plan', 'Floor Plan'), ('valuation', 'Valuation Report'), ('municipal', 'Municipal Account'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Display name — auto-filled from filename if blank', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, help_text='Leave blank for property-level documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.unit')),
            ],
            options={
                'ordering': ['doc_type', '-uploaded_at'],
            },
        ),
    ]
