# Generated by Django 5.2.12 on 2026-04-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_add_house_rules_and_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='doc_type',
            field=models.CharField(choices=[('offer_to_purchase', 'Offer to Purchase'), ('title_deed', 'Title Deed'), ('transfer_docs', 'Transfer Documents'), ('valuation', 'Valuation Report'), ('municipal', 'Municipal Account / Bill'), ('rates_clearance', 'Rates Clearance Certificate'), ('compliance_cert', 'Compliance Certificate'), ('technical_drawing', 'Technical Drawing / Floor Plan'), ('dev_handover', 'Developer Handover'), ('warranty', 'Warranty / Guarantee'), ('paint_spec', 'Paint Colours / Finishes'), ('generator', 'Generator / Inverter Info'), ('estate_rules', 'Estate / Complex Rules'), ('body_corporate', 'Body Corporate / HOA'), ('insurance', 'Insurance Document'), ('capital_upgrade', 'Capital Upgrade Invoice'), ('house_rules', 'House Rules'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
