# Generated by Django 5.2.12 on 2026-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_expand_doc_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='doc_type',
            field=models.CharField(choices=[('offer_to_purchase', 'Offer to Purchase'), ('title_deed', 'Title Deed'), ('transfer_docs', 'Transfer Documents'), ('valuation', 'Valuation Report'), ('compliance_cert', 'Compliance Certificate (general)'), ('electrical_coc', 'Electrical Certificate of Compliance'), ('gas_coc', 'Gas Compliance Certificate'), ('plumbing_coc', 'Plumbing Compliance Certificate'), ('beetle_cert', 'Beetle / Pest Certificate'), ('fence_cert', 'Electric Fence Certificate'), ('municipal', 'Municipal Account / Bill'), ('rates_clearance', 'Rates Clearance Certificate'), ('zoning_cert', 'Zoning Certificate'), ('building_plans', 'Approved Building Plans'), ('technical_drawing', 'Technical Drawing / Floor Plan'), ('dev_handover', 'Developer Handover'), ('warranty', 'Warranty / Guarantee'), ('paint_spec', 'Paint Colours / Finishes'), ('generator', 'Generator / Inverter Info'), ('solar', 'Solar / PV System Docs'), ('insurance', 'Insurance Document'), ('bond_docs', 'Bond / Mortgage Documents'), ('capital_upgrade', 'Capital Upgrade Invoice'), ('estate_rules', 'Estate / Complex Rules'), ('body_corporate', 'Body Corporate / HOA Minutes'), ('hoa_levy', 'HOA Levy Statement'), ('fica_docs', 'FICA Documentation'), ('tenant_id', 'Tenant ID Copy'), ('tenant_bank', 'Tenant Proof of Income / Bank'), ('credit_check', 'Credit Check Report'), ('house_rules', 'House Rules'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
