# Generated by Django 5.2.12 on 2026-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_fix_unitinfo_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='registration_document',
            field=models.FileField(blank=True, help_text='CIPC certificate, trust deed, or ID document', null=True, upload_to='landlords/registration_docs/'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='registration_document_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255),
        ),
    ]
