# Generated by Django 5.2.12 on 2026-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_landlord_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='classification_data',
            field=models.JSONField(blank=True, help_text='Structured output from the AI document classifier (owner_classification.json)', null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='mandate_document',
            field=models.FileField(blank=True, help_text='Signed management mandate / agency agreement', null=True, upload_to='landlords/mandates/'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='mandate_document_name',
            field=models.CharField(blank=True, help_text='Original filename', max_length=255),
        ),
        migrations.AddField(
            model_name='landlord',
            name='mandate_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='mandate_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='mandate_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='owned_by_trust',
            field=models.BooleanField(default=False, help_text='For companies/CCs — indicates beneficial ownership through a trust (triggers trust FICA/CIPC doc requirements)'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('trust', 'Trust'), ('cc', 'Close Corporation'), ('partnership', 'Partnership')], default='individual', max_length=20),
        ),
    ]
