# Generated by Django 5.2.12 on 2026-04-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_landlord_cc_partnership_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='landlords/documents/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.landlord')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
