# Generated by Django 5.2.12 on 2026-04-06 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esigning', '0010_remove_docuseal_fields'),
        ('properties', '0016_landlord_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='mandate_document',
            field=models.FileField(blank=True, help_text='DEPRECATED — use RentalMandate. Signed management mandate / agency agreement', null=True, upload_to='landlords/mandates/'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='mandate_document_name',
            field=models.CharField(blank=True, help_text='DEPRECATED — original filename', max_length=255),
        ),
        migrations.CreateModel(
            name='RentalMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandate_type', models.CharField(choices=[('full_management', 'Full Management'), ('letting_only', 'Letting Only'), ('rent_collection', 'Rent Collection Only'), ('finders_fee', 'Finders Fee')], max_length=20)),
                ('exclusivity', models.CharField(choices=[('sole', 'Sole Mandate'), ('open', 'Open Mandate')], default='sole', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Percentage for monthly mandates (e.g. 10.00 = 10%) or month count for once-off (e.g. 1.00 = 1 month)', max_digits=6)),
                ('commission_period', models.CharField(choices=[('monthly', 'Monthly'), ('once_off', 'Once-off')], default='monthly', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(default=60, help_text="Days' written notice required to terminate the mandate")),
                ('maintenance_threshold', models.DecimalField(decimal_places=2, default=2000, help_text='Full Management: max spend per incident the agent may authorise without owner approval (ZAR)', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signing'), ('partially_signed', 'Partially Signed'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('signed_document', models.FileField(blank=True, help_text='Final countersigned mandate PDF (auto-populated when e-signing completes)', null=True, upload_to='mandates/signed/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mandates', to=settings.AUTH_USER_MODEL)),
                ('esigning_submission', models.OneToOneField(blank=True, help_text='The e-signing submission that captured both owner and agent signatures', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='esigning.esigningsubmission')),
                ('landlord', models.ForeignKey(blank=True, help_text='Linked landlord entity (denormalised from PropertyOwnership for convenience)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandates', to='properties.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
