# Generated by Django 5.2.12 on 2026-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_add_property_viewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='properties/thumbnails/'),
        ),
    ]
