# Generated by Django 5.2.12 on 2026-04-14 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_add_photo_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('estate', 'Estate Agent (transaction)'), ('managing', 'Managing Agent (ongoing)')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mandate', models.ForeignKey(blank=True, help_text='Mandate under which this assignment was made', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_assignments', to='properties.rentalmandate')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='properties.property')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', 'status'], name='properties__agent_i_f9dfba_idx'), models.Index(fields=['property', 'status'], name='properties__propert_a0b5c8_idx')],
                'unique_together': {('property', 'agent')},
            },
        ),
    ]
