# Generated by Django 5.2.12 on 2026-04-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_propertyagentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='confirmation_letter',
            field=models.FileField(blank=True, null=True, upload_to='bank_accounts/confirmation_letters/'),
        ),
    ]
