# Generated by Django 5.2.12 on 2026-04-14 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_bankaccount_confirmation_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField(blank=True, help_text='Plain-text content of the message.')),
                ('tool_calls', models.JSONField(blank=True, help_text='Tool use / tool result blocks for this turn.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='properties.landlord')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['landlord', 'created_at'], name='properties__landlor_b7ff0a_idx')],
            },
        ),
    ]
