# Generated by Django 5.2.13 on 2026-04-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_merge_unit_features_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmandate',
            name='previous_mandate',
            field=models.ForeignKey(blank=True, help_text='The mandate this one was cloned from during renewal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='properties.rentalmandate'),
        ),
        migrations.AddField(
            model_name='rentalmandate',
            name='terminated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the mandate was formally terminated', null=True),
        ),
        migrations.AddField(
            model_name='rentalmandate',
            name='terminated_reason',
            field=models.TextField(blank=True, help_text='Written reason / notice provided by the terminating party'),
        ),
        migrations.AlterField(
            model_name='rentalmandate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signing'), ('partially_signed', 'Partially Signed'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], default='draft', max_length=20),
        ),
    ]
