# Generated by Django 5.2.12 on 2026-05-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('properties', '0027_mandate_termination_renewal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. A landlord belongs to exactly one agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landlords', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='anonymisation_reason',
            field=models.CharField(blank=True, choices=[('dsar_deletion', 'Subject requested deletion (s24)'), ('retention_expired', 'Retention window expired (s14)'), ('agency_offboarding', 'Agency closed account / cancelled subscription'), ('data_quality', 'Record corrected — superseded data anonymised'), ('operator_decision', 'Klikk operator decision (rare)')], default='', help_text='Why this record was anonymised (POPIA s23/s24 audit trail).', max_length=32),
        ),
        migrations.AddField(
            model_name='landlord',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='is_anonymised',
            field=models.BooleanField(default=False, help_text='True after PII fields have been scrubbed per a DSAR or retention policy.'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text="POPIA s11 basis for the landlord's PI.", max_length=32),
        ),
        migrations.AddField(
            model_name='landlord',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention. Default 5 years (FICA s42/s43).', max_length=32),
        ),
        migrations.AddField(
            model_name='landlord',
            name='vault_entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Vault33 VaultEntity PK once landlord identity is mirrored.', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Properties never cross agencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='property',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text="POPIA s11 basis. Default 'contract' — most rental flows.", max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text="POPIA s14 retention obligation for this property's records.", max_length=32),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['agency', 'name'], name='landlord_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['vault_entity_id'], name='landlord_vault_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agency', '-created_at'], name='property_agency_created_idx'),
        ),
    ]
