# Generated by Django 5.2.12 on 2026-05-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
        ('esigning', '0011_add_rental_mandate'),
        ('leases', '0023_expire_stale_active_leases'),
        ('properties', '0029_backfill_agency_id_property_landlord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — banking detail under FICA legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention — FICA s42/s43 (5 years).', max_length=32),
        ),
        migrations.AddField(
            model_name='compliancecertificate',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_certificates', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='compliancecertificate',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — compliance certs held under legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='compliancecertificate',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention — RHA 3-year dispute window.', max_length=32),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention — SARS 7-year audit window.', max_length=32),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention — SARS 7-year audit window.', max_length=32),
        ),
        migrations.AddField(
            model_name='landlordchatmessage',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landlord_chat_messages', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='landlordchatmessage',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='landlordchatmessage',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention — onboarding chat lives with relationship.', max_length=32),
        ),
        migrations.AddField(
            model_name='landlorddocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landlord_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='landlorddocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — FICA/CIPC docs are processed under legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='landlorddocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention — FICA s42/s43 (5 years).', max_length=32),
        ),
        migrations.AddField(
            model_name='municipalaccount',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipal_accounts', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='municipalaccount',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — municipal data held under legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='municipalaccount',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention — SARS 7-year audit window.', max_length=32),
        ),
        migrations.AddField(
            model_name='municipalbill',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipal_bills', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='municipalbill',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — utility bills retained under legal/SARS obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='municipalbill',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention — SARS 7-year audit window.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyagentassignment',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_agent_assignments', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyagentassignment',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyagentassignment',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyagentconfig',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_agent_configs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyagentconfig',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyagentconfig',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_details', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_groups', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_ownerships', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 — owner identity processed under FICA legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention — FICA s42/s43.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_photos', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyvaluation',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_valuations', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyvaluation',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyvaluation',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention — SARS 7-year audit window.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_viewings', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis — pre-contractual interaction.', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyviewing',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='rha_3yr', help_text='POPIA s14 retention — RHA 3-year window for prospect interactions.', max_length=32),
        ),
        migrations.AddField(
            model_name='rentalmandate',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_mandates', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='rentalmandate',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 — mandate is the agency-owner contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='rentalmandate',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention — FICA s42/s43.', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='room',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from parent property.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text="POPIA s11 basis. Default 'contract' — leasing flow.", max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='unitinfo',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_info_items', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='unitinfo',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis.', max_length=32),
        ),
        migrations.AddField(
            model_name='unitinfo',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['agency', 'landlord'], name='bankacct_agency_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecertificate',
            index=models.Index(fields=['agency', 'expiry_date'], name='cert_agency_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['agency', 'status'], name='insclaim_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['agency', 'is_active'], name='inspolicy_agency_active_idx'),
        ),
        migrations.AddIndex(
            model_name='landlordchatmessage',
            index=models.Index(fields=['agency', 'created_at'], name='llchat_agency_created_idx'),
        ),
        migrations.AddIndex(
            model_name='landlorddocument',
            index=models.Index(fields=['agency', 'landlord'], name='lldoc_agency_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='municipalaccount',
            index=models.Index(fields=['agency', 'account_type'], name='muniacct_agency_type_idx'),
        ),
        migrations.AddIndex(
            model_name='municipalbill',
            index=models.Index(fields=['agency', 'due_date'], name='munibill_agency_due_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagentassignment',
            index=models.Index(fields=['agency', 'status'], name='paassign_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyagentconfig',
            index=models.Index(fields=['agency', 'is_active'], name='propagentcfg_agency_active_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydetail',
            index=models.Index(fields=['agency', 'suburb'], name='propdetail_agency_suburb_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['agency', 'doc_type'], name='propdoc_agency_doctype_idx'),
        ),
        migrations.AddIndex(
            model_name='propertygroup',
            index=models.Index(fields=['agency', 'name'], name='propgroup_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyownership',
            index=models.Index(fields=['agency', 'is_current'], name='ownership_agency_current_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyphoto',
            index=models.Index(fields=['agency', 'property'], name='photo_agency_property_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvaluation',
            index=models.Index(fields=['agency', 'valuation_date'], name='valuation_agency_date_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyviewing',
            index=models.Index(fields=['agency', 'scheduled_at'], name='viewing_agency_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalmandate',
            index=models.Index(fields=['agency', 'status'], name='mandate_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['agency', 'unit'], name='room_agency_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['agency', 'status'], name='unit_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unitinfo',
            index=models.Index(fields=['agency', 'property'], name='unitinfo_agency_property_idx'),
        ),
    ]
