# Generated by Django 5.2.12 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_backfill_orphans_to_agency_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='electricity_arrangement',
            field=models.CharField(choices=[('prepaid', 'Prepaid electricity'), ('eskom_direct', 'Direct Eskom account'), ('included', 'Included in rent'), ('not_included', 'Tenant arranges separately')], default='not_included', help_text='Default electricity arrangement (lease may override).', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='gardening_service_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security_service_included',
            field=models.BooleanField(default=False, help_text='Armed response / monitoring service.'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_arrangement',
            field=models.CharField(choices=[('included', 'Water included in rent'), ('not_included', 'Water not included')], default='not_included', help_text='Default water arrangement (lease may override).', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_included',
            field=models.BooleanField(default=False),
        ),
    ]
