# Generated by Django 5.2.12 on 2026-04-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_tests', models.IntegerField(default=0)),
                ('total_green', models.IntegerField(default=0)),
                ('total_red', models.IntegerField(default=0)),
                ('total_unit', models.IntegerField(default=0)),
                ('total_integration', models.IntegerField(default=0)),
                ('total_e2e', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('fixed_issues', models.IntegerField(default=0)),
                ('avg_days_to_fix', models.FloatField(blank=True, null=True)),
                ('coverage_percent', models.FloatField(blank=True, null=True)),
                ('rag_last_indexed', models.DateTimeField(blank=True, null=True)),
                ('module_breakdown', models.JSONField(default=dict, help_text='Per-module test counts')),
            ],
            options={
                'verbose_name': 'Test Health Snapshot',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='TestModuleSelfHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('context_files_ok', models.BooleanField(default=False, help_text='All 8 module context files exist and are non-empty')),
                ('rag_store_ok', models.BooleanField(default=False, help_text='test_context ChromaDB collection has documents')),
                ('rag_last_indexed', models.DateTimeField(blank=True, null=True)),
                ('all_modules_have_tests', models.BooleanField(default=False, help_text='Every module has at least one unit/ and integration/ test')),
                ('issues_synced', models.BooleanField(default=False, help_text='All issue .md files have matching TestIssue DB records')),
                ('no_duplicate_test_names', models.BooleanField(default=False, help_text='No duplicate test method names across the suite')),
                ('no_orphaned_files', models.BooleanField(default=False, help_text='All test directories have __init__.py')),
                ('conftest_enforces_xfail', models.BooleanField(default=False, help_text='conftest.py enforces xfail strict on @pytest.mark.red')),
                ('issues_found', models.JSONField(default=list, help_text='List of integrity issues found during self-check')),
                ('warnings', models.JSONField(default=list, help_text='Non-critical warnings')),
            ],
            options={
                'verbose_name': 'Test Module Self-Health',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounts', 'Accounts'), ('properties', 'Properties'), ('leases', 'Leases'), ('maintenance', 'Maintenance'), ('esigning', 'Esigning'), ('ai', 'Ai'), ('tenant_portal', 'Tenant Portal'), ('notifications', 'Notifications'), ('all', 'All')], db_index=True, max_length=50)),
                ('tier', models.CharField(choices=[('unit', 'Unit'), ('integration', 'Integration'), ('e2e', 'E2E'), ('all', 'All')], default='all', max_length=20)),
                ('phase', models.CharField(choices=[('red', 'Red (pending)'), ('green', 'Green (passing)'), ('all', 'All')], default='all', max_length=20)),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('ai_agent', 'AI Agent'), ('ci', 'CI/CD'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('tests_run', models.IntegerField(default=0)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_failed', models.IntegerField(default=0)),
                ('tests_xfailed', models.IntegerField(default=0)),
                ('tests_xpassed', models.IntegerField(default=0)),
                ('tests_skipped', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('coverage_percent', models.FloatField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Test Run Record',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='TestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('accounts', 'Accounts'), ('properties', 'Properties'), ('leases', 'Leases'), ('maintenance', 'Maintenance'), ('esigning', 'Esigning'), ('ai', 'Ai'), ('tenant_portal', 'Tenant Portal'), ('notifications', 'Notifications')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('red', 'RED — fix pending'), ('fixed', 'FIXED — test green')], db_index=True, default='red', max_length=10)),
                ('discovered_at', models.DateField(db_index=True)),
                ('fixed_at', models.DateField(blank=True, null=True)),
                ('test_file', models.CharField(blank=True, help_text='Path to the red/green test', max_length=500)),
                ('issue_file_path', models.CharField(help_text='Path to the .md issue file', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Test Issue',
                'ordering': ['-discovered_at'],
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
