# Generated by Django 5.2.12 on 2026-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='SA ID or passport number', max_length=20),
        ),
    ]
