# Generated by Django 5.2.12 on 2026-03-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Agent'), ('admin', 'Admin'), ('supplier', 'Supplier'), ('owner', 'Owner')], default='tenant', max_length=10),
        ),
    ]
