# Generated by Django 5.2.12 on 2026-04-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginattempt_userinvite_authauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('eaab_ffc_number', models.CharField(blank=True, help_text='EAAB Fidelity Fund Certificate number', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('trust_account_number', models.CharField(blank=True, max_length=50)),
                ('trust_bank_name', models.CharField(blank=True, max_length=100)),
                ('statement_date', models.CharField(blank=True, default='the 5th', help_text='e.g. "the 5th"', max_length=30)),
                ('disbursement_date', models.CharField(blank=True, default='the 7th', help_text='e.g. "the 7th"', max_length=30)),
                ('information_officer_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
            },
        ),
    ]
