# Generated by Django 5.2.12 on 2026-04-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_agency_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='account_type',
            field=models.CharField(choices=[('agency', 'Estate Agency'), ('individual', 'Individual Owner')], default='agency', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='auditor_irba_number',
            field=models.CharField(blank=True, help_text='IRBA practice number', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='auditor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='bee_level',
            field=models.CharField(blank=True, help_text='e.g. Level 1, Level 4, Exempt', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='fica_registered',
            field=models.BooleanField(default=False, help_text='Registered as Accountable Institution with FIC'),
        ),
        migrations.AddField(
            model_name='agency',
            name='postal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='principal_name',
            field=models.CharField(blank=True, help_text='Principal property practitioner', max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='principal_ppra_number',
            field=models.CharField(blank=True, help_text='7-digit PPRA registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='trading_name',
            field=models.CharField(blank=True, help_text='Trading-as name shown on documents (e.g. t/a Century 21 Stellenbosch)', max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='trust_branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='eaab_ffc_number',
            field=models.CharField(blank=True, help_text='PPRA Fidelity Fund Certificate number', max_length=50),
        ),
        migrations.AlterField(
            model_name='agency',
            name='registration_number',
            field=models.CharField(blank=True, help_text='CIPC registration number', max_length=50),
        ),
    ]
