# Generated by Django 5.2.12 on 2026-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_agency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross monthly income in ZAR', max_digits=12, null=True),
        ),
    ]
