# Generated by Django 5.2.12 on 2026-04-14 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userinvite_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this user belongs to (agents, agency admin, viewers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='user',
            name='ffc_category',
            field=models.CharField(blank=True, choices=[('estate', 'Estate Agent'), ('managing', 'Managing Agent')], help_text='FFC category — distinct from role (regulatory classification)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ffc_number',
            field=models.CharField(blank=True, help_text='Individual Fidelity Fund Certificate number (PPA requirement)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='module_access',
            field=models.JSONField(blank=True, default=list, help_text='Module access flags for viewer role, e.g. ["inspections","maintenance","properties"]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Agent'), ('admin', 'Admin'), ('supplier', 'Supplier'), ('owner', 'Owner'), ('agency_admin', 'Agency Admin'), ('estate_agent', 'Estate Agent'), ('managing_agent', 'Managing Agent'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], default='tenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Agent'), ('admin', 'Admin'), ('supplier', 'Supplier'), ('owner', 'Owner'), ('agency_admin', 'Agency Admin'), ('estate_agent', 'Estate Agent'), ('managing_agent', 'Managing Agent'), ('accountant', 'Accountant'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
