# Generated by Django 5.2.12 on 2026-04-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_agency_is_active_user_agency_user_ffc_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency to assign when invite is accepted (for agent/viewer roles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='accounts.agency'),
        ),
    ]
