# Generated by Django 5.2.12 on 2026-04-14 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userinvite_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'ID / Passport Copy'), ('proof_of_address', 'Proof of Address'), ('proof_of_income', 'Proof of Income'), ('fica', 'FICA / KYC Document'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='person_documents/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.person')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
