# Generated by Django 5.2.12 on 2026-04-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usertotp_totprecoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in ZAR excl VAT. Null = quoted (enterprise/custom).', max_digits=10, null=True)),
                ('features', models.JSONField(default=dict, help_text='Boolean feature flag dict.')),
                ('quotas', models.JSONField(default=dict, help_text='Numeric quota dict (None = unlimited).')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_tier',
            field=models.ForeignKey(blank=True, help_text='Pricing tier — null means all features are accessible (backwards compat).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies', to='accounts.subscriptiontier'),
        ),
    ]
