# Generated by Django 5.2.13 on 2026-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_welcome_at',
            field=models.DateTimeField(blank=True, help_text='When the tenant first dismissed the welcome screen; null = not yet seen.', null=True),
        ),
    ]
