# Generated by Django 5.2.13 on 2026-04-23 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_seen_welcome_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('issued', 'OTP Issued'), ('verify_success', 'Verify Success'), ('verify_fail', 'Verify Fail'), ('rate_limited', 'Rate Limited'), ('expired', 'Expired'), ('locked', 'Locked (max attempts)')], max_length=20)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Audit Log',
                'verbose_name_plural': 'OTP Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='accounts_ot_user_id_1830c2_idx'), models.Index(fields=['created_at'], name='accounts_ot_created_86a5ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPCodeV1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text="Scopes the code — e.g. 'registration', 'password_reset', 'sensitive_change'.", max_length=64)),
                ('code_hash', models.CharField(help_text='HMAC-SHA256 hex digest of the plaintext code. Never store plaintext.', max_length=128)),
                ('channel_used', models.CharField(help_text="Channel that delivered this code, e.g. 'email' or 'sms'.", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, help_text='Set when the code is successfully verified and consumed.', null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verify attempts against this code.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_v2_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'db_table': 'accounts_otp_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='accounts_ot_user_id_e13f06_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_3f6bc9_idx')],
            },
        ),
    ]
