# Generated by Django 5.2.12 on 2026-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_otp_code_v1_and_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web Push')], max_length=10),
        ),
    ]
