# Generated by Django 5.2.13 on 2026-04-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_web_push_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skipped_2fa_setup_at',
            field=models.DateTimeField(blank=True, help_text='When an optional-2FA user (e.g. owner) last skipped the 2FA setup prompt. Null means they have not been prompted yet or never skipped.', null=True),
        ),
    ]
