# Generated by Django 5.2.13 on 2026-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_skipped_2fa_setup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa_method',
            field=models.CharField(choices=[('totp', 'Authenticator App (TOTP)'), ('email', 'Email OTP')], default='totp', help_text='Second factor method used when 2FA is required for this account.', max_length=10),
        ),
    ]
