# Generated by Django 5.2.12 on 2026-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_two_fa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='authauditlog',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency when present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth_audit_logs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Auth audit = legal obligation (security records).', max_length=32),
        ),
        migrations.AddField(
            model_name='authauditlog',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Append-only audit; anonymise references when subject expires.', max_length=32),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Resolved from matching user.agency when known.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login_attempts', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Brute-force protection = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Security log; anonymise references when subject expires.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpauditlog',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency when present.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_audit_logs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='otpauditlog',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. OTP audit = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpauditlog',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Append-only audit; anonymise references when subject expires.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_codes', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. OTP = security operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors user lifecycle.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpcodev1',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_v1_codes', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='otpcodev1',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. OTP = security operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='otpcodev1',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Short-lived; expiry-driven cleanup.', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Person is per-agency (full isolation).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='person',
            name='anonymisation_reason',
            field=models.CharField(blank=True, choices=[('dsar_deletion', 'Subject requested deletion (s24)'), ('retention_expired', 'Retention window expired (s14)'), ('agency_offboarding', 'Agency closed account / cancelled subscription'), ('data_quality', 'Record corrected — superseded data anonymised'), ('operator_decision', 'Klikk operator decision (rare)')], default='', help_text='Why this record was anonymised (POPIA s23/s24 audit trail).', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_anonymised',
            field=models.BooleanField(default=False, help_text='True after PII fields have been scrubbed per a DSAR or retention policy.'),
        ),
        migrations.AddField(
            model_name='person',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Person captured under lease = performance of contract.', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors the parent relationship lifecycle.', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='vault_entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Vault33 VaultEntity PK once person identity is mirrored.', null=True),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from person.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_documents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. FICA/ID documents = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_5yr', help_text='POPIA s14 retention. Default 5 years (FICA s42/s43).', max_length=32),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='push_tokens', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Push tokens are operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='pushtoken',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors user lifecycle.', max_length=32),
        ),
        migrations.AddField(
            model_name='totprecoverycode',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='totp_recovery_codes', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='totprecoverycode',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Recovery codes = security operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='totprecoverycode',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors user lifecycle.', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymisation_reason',
            field=models.CharField(blank=True, choices=[('dsar_deletion', 'Subject requested deletion (s24)'), ('retention_expired', 'Retention window expired (s14)'), ('agency_offboarding', 'Agency closed account / cancelled subscription'), ('data_quality', 'Record corrected — superseded data anonymised'), ('operator_decision', 'Klikk operator decision (rare)')], default='', help_text='Why this record was anonymised (POPIA s23/s24 audit trail).', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_anonymised',
            field=models.BooleanField(default=False, help_text='True after PII fields have been scrubbed per a DSAR or retention policy.'),
        ),
        migrations.AddField(
            model_name='user',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='contract', help_text='POPIA s11 basis. Auth users normally CONTRACT (employment / portal access).', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors lease lifecycle for tenant users.', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='vault_entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Vault33 VaultEntity PK once user identity is mirrored.', null=True),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. Invitations are transient operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='userinvite',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='none', help_text='POPIA s14 retention. Transient — no automated retention.', max_length=32),
        ),
        migrations.AddField(
            model_name='usertotp',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_totps', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='usertotp',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='operator_instruction', help_text='POPIA s11 basis. TOTP secrets = security operator-instruction.', max_length=32),
        ),
        migrations.AddField(
            model_name='usertotp',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='lease_lifetime', help_text='POPIA s14 retention. Mirrors user lifecycle.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='authauditlog',
            index=models.Index(fields=['agency', 'event_type'], name='auth_agency_event_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['agency', 'succeeded'], name='loginatt_agency_ok_idx'),
        ),
        migrations.AddIndex(
            model_name='otpauditlog',
            index=models.Index(fields=['agency', 'event_type'], name='otpaudit_agency_event_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['agency', 'full_name'], name='person_agency_name_idx'),
        ),
        migrations.AddIndex(
            model_name='persondocument',
            index=models.Index(fields=['agency', 'document_type'], name='persondoc_agency_type_idx'),
        ),
    ]
