# Generated by Django 5.2.12 on 2026-05-07 — Phase 3.2

from django.db import migrations, models


def backfill_onboarding_completed_at(apps, schema_editor):
    """Stamp existing 'real' agencies as already-onboarded.

    Heuristic: Agency has a `name` AND a non-empty `physical_address` →
    treat it as set up before Phase 3.2 and stamp `onboarding_completed_at`
    so existing customers don't get punted to the wizard on next login.
    """
    Agency = apps.get_model("accounts", "Agency")
    from django.utils import timezone as _tz

    now = _tz.now()
    qs = Agency.objects.filter(onboarding_completed_at__isnull=True).exclude(
        physical_address=""
    ).exclude(name="")
    count = qs.update(onboarding_completed_at=now)
    if count:
        # printed during migrate; harmless on empty databases
        print(f"  [accounts.0025] backfilled onboarding_completed_at on {count} agency row(s)")


def reverse_noop(apps, schema_editor):
    """Reverse: clear all backfilled timestamps."""
    Agency = apps.get_model("accounts", "Agency")
    Agency.objects.update(onboarding_completed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_backfill_agency_id_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='onboarding_completed_at',
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When the AGENCY_ADMIN finished the agency setup wizard. "
                    "Used by the router guard to redirect first-time users to /onboarding."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(backfill_onboarding_completed_at, reverse_noop),
    ]
