# Generated by Django 5.2.12 on 2026-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_backfill_orphan_users_to_agency_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, default='ZA', help_text="ISO 3166-1 alpha-2 country code (e.g. 'ZA', 'GB', 'NG'). Defaults to South Africa.", max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+27', help_text="E.164 country dialing code with leading + (e.g. '+27', '+44'). Defaults to South Africa.", max_length=4),
        ),
    ]
