# Generated by Django 5.2.12 on 2026-05-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestation_id', models.CharField(db_index=True, help_text="Stable id, e.g. '2026-Q2-attorney-review'.", max_length=80, unique=True)),
                ('attorney_name', models.CharField(max_length=200)),
                ('attorney_admission_number', models.CharField(help_text="LPC admission number, e.g. 'LPC-WC-12345'.", max_length=64)),
                ('attorney_firm', models.CharField(blank=True, max_length=200)),
                ('attestation_method', models.CharField(choices=[('email_pdf_signed', 'Email PDF Signed'), ('in_person_review', 'In-Person Review'), ('counsel_opinion_letter', 'Counsel Opinion Letter')], max_length=32)),
                ('attestation_date', models.DateField(db_index=True)),
                ('opinion_letter_pdf_sha256', models.CharField(blank=True, help_text='SHA256 of the signed opinion letter PDF for tamper-evidence.', max_length=64)),
                ('opinion_letter_storage', models.CharField(blank=True, help_text="Storage URI for the opinion letter PDF (e.g. 'vault33://...').", max_length=512)),
                ('scope', models.TextField(help_text='Human-readable scope of the opinion letter.')),
                ('cost_zar', models.DecimalField(blank=True, decimal_places=2, help_text='Fee in ZAR for this attestation.', max_digits=10, null=True)),
                ('facts_attested', models.JSONField(default=list, help_text='List of {concept_id, fact_version, finding, correction_summary?} entries — one per fact covered. See AttestationFinding for the allowed `finding` values.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Attestation',
                'verbose_name_plural': 'Legal Attestations',
                'ordering': ('-attestation_date',),
            },
        ),
        migrations.CreateModel(
            name='LegalCorpusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Corpus hash (sha256 hex of concatenated fact hashes).', max_length=64, unique=True)),
                ('merkle_root', models.CharField(help_text='Merkle-root-style sha256 over all fact content_hashes.', max_length=64)),
                ('embedding_model', models.CharField(help_text="Embedding model name locked at index time (e.g. 'text-embedding-3-small'). Drift = full re-index.", max_length=128)),
                ('fact_count', models.PositiveIntegerField(help_text='Total LegalFact rows captured by this corpus version.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='True for the version the runtime currently serves.')),
            ],
            options={
                'verbose_name': 'Legal Corpus Version',
                'verbose_name_plural': 'Legal Corpus Versions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.CharField(db_index=True, help_text="Globally unique kebab-case slug, e.g. 'rha-s5-3-f-deposit-interest-bearing-account'.", max_length=80, unique=True)),
                ('type', models.CharField(choices=[('statute_provision', 'Statute Provision'), ('case_law', 'Case Law'), ('pitfall', 'Pitfall Pattern'), ('concept', 'Cross-Statute Concept')], db_index=True, help_text='Top-level fact kind. See FactType.', max_length=32)),
                ('citation_string', models.CharField(db_index=True, help_text="Canonical render, e.g. 'RHA s5(3)(f)'.", max_length=120)),
                ('plain_english_summary', models.TextField(help_text='The fact in 1-3 sentences, suitable for end-user display.')),
                ('statute_text', models.TextField(blank=True, help_text='Statute text body. May be paraphrased; see statute_text_verbatim.')),
                ('statute_text_verbatim', models.BooleanField(default=False, help_text='True only when an admitted attorney has confirmed the text against the current consolidated Act. Setting True requires verification_status=lawyer_reviewed.')),
                ('citation_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, help_text='Per the canonical citation map taxonomy.', max_length=16)),
                ('legal_provisional', models.BooleanField(db_index=True, default=False, help_text='If true, consumers MUST surface uncertainty to the end user (disclaimers + UI affordance).')),
                ('verification_status', models.CharField(choices=[('ai_curated', 'AI Curated'), ('mc_reviewed', 'MC Reviewed'), ('lawyer_reviewed', 'Lawyer Reviewed')], db_index=True, help_text='Editorial review state.', max_length=32)),
                ('fact_version', models.PositiveIntegerField(default=1, help_text='Monotonic version counter — bumps on every content change.')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 of the canonical YAML source for this version.', max_length=64)),
                ('applicability', models.JSONField(blank=True, default=dict, help_text='Retrieval filter. Shape: {property_types, tenant_counts, lease_types, jurisdictions}. See plan §4.')),
                ('topic_tags', models.JSONField(blank=True, default=list, help_text='List[str]. Used for tag-and-filter retrieval.')),
                ('disclaimers', models.JSONField(blank=True, default=list, help_text='List[str] of consumer-mandatory disclaimers attached to this fact.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = the YAML was deleted; row retained for history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corpus_version', models.ForeignKey(help_text='Corpus snapshot this row was published in.', on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='legal_rag.legalcorpusversion')),
            ],
            options={
                'verbose_name': 'Legal Fact',
                'verbose_name_plural': 'Legal Facts',
                'ordering': ('concept_id',),
            },
        ),
        migrations.CreateModel(
            name='LegalFactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Matches LegalFact.fact_version at the time this row was created.')),
                ('content', models.JSONField(help_text='Full canonical YAML body for this version, as a dict.')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 of the canonical YAML source for this version.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attestation', models.ForeignKey(blank=True, help_text='If non-null, this version was attested by the linked attorney opinion event. Null until first attestation lands.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_versions', to='legal_rag.legalattestation')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='legal_rag.legalfact')),
            ],
            options={
                'verbose_name': 'Legal Fact Version',
                'verbose_name_plural': 'Legal Fact Versions',
                'ordering': ('fact_id', '-version'),
            },
        ),
        migrations.AddField(
            model_name='legalfact',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='FK to the LegalFactVersion row whose content matches the columns above.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='legal_rag.legalfactversion'),
        ),
        migrations.AddConstraint(
            model_name='legalfactversion',
            constraint=models.UniqueConstraint(fields=('fact', 'version'), name='legal_rag_fact_version_unique'),
        ),
        migrations.AddIndex(
            model_name='legalfact',
            index=models.Index(fields=['type', 'verification_status'], name='legal_rag_l_type_ff1cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='legalfact',
            index=models.Index(fields=['citation_string', 'verification_status'], name='legal_rag_l_citatio_56c6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='legalfact',
            index=models.Index(fields=['citation_confidence', 'legal_provisional'], name='legal_rag_l_citatio_e637b9_idx'),
        ),
    ]
