import io
import re
import base64
import logging
import requests
from django.conf import settings

logger = logging.getLogger(__name__)


def _docuseal_headers():
    key = (getattr(settings, 'DOCUSEAL_API_KEY', '') or '').strip()
    if not key:
        raise ValueError(
            'DOCUSEAL_API_KEY is empty. Set it in backend/.env to the API token from your DocuSeal '
            'instance (same token that works in Postman), then restart Django.'
        )
    return {'X-Auth-Token': key, 'Content-Type': 'application/json'}


def _docuseal_base():
    return getattr(settings, 'DOCUSEAL_API_URL', 'https://api.docuseal.com').rstrip('/')


def _docuseal_post(path, payload, *, timeout=30):
    url = f"{_docuseal_base()}{path}"
    resp = requests.post(url, headers=_docuseal_headers(), json=payload, timeout=timeout)
    if not resp.ok:
        body = (resp.text or '')[:2000]
        logger.error('DocuSeal API error %s %s — %s', resp.status_code, url, body)
    resp.raise_for_status()
    return resp.json()


def _docuseal_get(path, *, timeout=15):
    url = f"{_docuseal_base()}{path}"
    resp = requests.get(url, headers=_docuseal_headers(), timeout=timeout)
    resp.raise_for_status()
    return resp.json()


def _docuseal_put(path, payload, *, timeout=30):
    url = f"{_docuseal_base()}{path}"
    resp = requests.put(url, headers=_docuseal_headers(), json=payload, timeout=timeout)
    if not resp.ok:
        body = (resp.text or '')[:2000]
        logger.error('DocuSeal API error %s %s — %s', resp.status_code, url, body)
    resp.raise_for_status()
    return resp.json()


def get_submitter(submitter_id: int) -> dict:
    """Fetch submitter details from DocuSeal (includes documents, status)."""
    return _docuseal_get(f'/submitters/{submitter_id}')


def get_template_fields(template_id: int) -> dict:
    """Fetch template details including field definitions and positions."""
    return _docuseal_get(f'/templates/{template_id}')


def submit_signature(submitter_id: int, fields: list) -> dict:
    """
    Submit signature data to DocuSeal and mark the submitter as completed.

    fields = [
        {'name': 'Signature (First Party)', 'default_value': 'data:image/png;base64,...'},
        {'name': 'Date (First Party)', 'default_value': '2026-03-26'},
    ]
    """
    return _docuseal_put(f'/submitters/{submitter_id}', {
        'completed': True,
        'fields': fields,
    })


def get_document_pdf_url(submitter_id: int) -> str | None:
    """Get the PDF URL for a submitter's document from DocuSeal."""
    data = get_submitter(submitter_id)
    docs = data.get('documents') or []
    if docs:
        return docs[0].get('url')
    return None


def _count_pdf_pages(pdf_bytes: bytes) -> int:
    """Count pages in a PDF. Uses pypdf if available, falls back to regex."""
    try:
        from pypdf import PdfReader
        reader = PdfReader(io.BytesIO(pdf_bytes))
        return len(reader.pages)
    except Exception:
        pass
    # Fallback: regex on the raw bytes (less reliable)
    try:
        import re as _re
        m = _re.search(rb'/Type\s*/Pages\b[^>]*/Count\s+(\d+)', pdf_bytes)
        if m:
            return int(m.group(1))
    except Exception:
        pass
    return 1


def upload_pdf_template(pdf_bytes: bytes, name: str, num_signers: int = 1) -> dict:
    """Upload a PDF to DocuSeal with signature fields so submissions can be created.

    Signature fields are placed on the LAST page (the dedicated signature page
    generated by generate_lease_pdf), aligned with the visual signature line blocks.
    Each signer block occupies ~18% of page height, starting from y≈0.20.
    """
    b64 = base64.b64encode(pdf_bytes).decode()
    last_page = _count_pdf_pages(pdf_bytes)

    fields = []
    for i in range(num_signers):
        role = 'First Party' if i == 0 else f'Signer {i + 1}'
        # Each signature block is spaced evenly on the signature page.
        # The signature lines in the HTML start at roughly y=0.20 and each
        # block is ~0.18 tall (signature + date + label).
        y_sig = 0.22 + (i * 0.18)
        y_date = y_sig + 0.08
        fields.extend([
            {
                'name': f'Signature ({role})',
                'type': 'signature',
                'role': role,
                'required': True,
                'areas': [{'x': 0.05, 'y': y_sig, 'w': 0.35, 'h': 0.06, 'page': last_page}],
            },
            {
                'name': f'Date ({role})',
                'type': 'date',
                'role': role,
                'required': True,
                'areas': [{'x': 0.05, 'y': y_date, 'w': 0.20, 'h': 0.04, 'page': last_page}],
            },
        ])

    doc_name = name if not name.endswith('.pdf') else name
    return _docuseal_post('/templates/pdf', {
        'name': name,
        'documents': [{
            'name': f'{doc_name}.pdf',
            'file': b64,
            'fields': fields,
        }],
    }, timeout=120)


def create_submission(template_id: int, submitters: list, send_email: bool = True) -> dict:
    """
    Create a DocuSeal submission.
    submitters = [{'name': '...', 'email': '...', 'role': '...', 'send_email': True, 'order': 0}]
    The 'order' field controls sequential signing: DocuSeal holds back higher-order
    signers until all lower-order signers have completed.  Omitting 'order' (or giving
    everyone the same value) makes everyone sign in parallel.
    Returns the submissions list from DocuSeal.
    """
    return _docuseal_post('/submissions', {
        'template_id': template_id,
        'send_email': send_email,
        'submitters': submitters,
    })


def _roles_from_template(template_data: dict) -> list[str]:
    """DocuSeal `role` on each submitter must match `submitters[].name` on the template."""
    subs = template_data.get('submitters') or []
    roles = [s.get('name') for s in subs if s.get('name')]
    return [r for r in roles if r]


def build_lease_context(lease) -> dict:
    """Map a Lease ORM object to merge-field key/value pairs."""
    unit = lease.unit
    prop = unit.property
    tenant = lease.primary_tenant

    ctx = {
        'landlord_name':    getattr(prop, 'owner', None) and prop.owner.full_name or '—',
        'property_address': prop.address or '—',
        'property_name':    prop.name or '—',
        'unit_number':      unit.unit_number,
        'city':             getattr(prop, 'city', '') or '—',
        'province':         getattr(prop, 'province', '') or '—',
        'tenant_name':      tenant.full_name if tenant else '—',
        'tenant_id':        tenant.id_number if tenant else '—',
        'tenant_phone':     tenant.phone if tenant else '—',
        'tenant_email':     tenant.email if tenant else '—',
        'lease_start':      str(lease.start_date),
        'lease_end':        str(lease.end_date),
        'monthly_rent':     f'R {lease.monthly_rent:,.2f}',
        'deposit':          f'R {lease.deposit:,.2f}',
        'notice_period_days': str(getattr(lease, 'notice_period_days', 30)),
        'water_included':   'Included' if getattr(lease, 'water_included', True) else 'Excluded',
        'electricity_prepaid': 'Prepaid' if getattr(lease, 'electricity_prepaid', True) else 'Included in rent',
        'max_occupants':    str(getattr(lease, 'max_occupants', 1)),
        'payment_reference': getattr(lease, 'payment_reference', '') or '—',
    }
    co = list(lease.co_tenants.select_related('person').all())
    ctx['co_tenants'] = ', '.join(ct.person.full_name for ct in co if ct.person.full_name) or '—'
    return ctx


def generate_lease_pdf(lease) -> bytes:
    """
    Generate a filled PDF for the lease.
    Uses the first active LeaseTemplate; falls back to a plain-text layout.
    Returns PDF bytes.
    """
    from apps.leases.models import LeaseTemplate
    from xhtml2pdf import pisa

    ctx = build_lease_context(lease)
    # Prefer the most recently created active template that has HTML content.
    tmpl = (
        LeaseTemplate.objects.filter(is_active=True).exclude(content_html='')
        .order_by('-id').first()
        or LeaseTemplate.objects.filter(is_active=True).order_by('-id').first()
    )

    if tmpl and tmpl.content_html:
        html_body = tmpl.content_html

        def replace_field(m):
            field = m.group(1)
            val = ctx.get(field, f'{{ {field} }}')
            return f'<span class="filled">{val}</span>'

        html_body = re.sub(
            r'<span[^>]+data-merge-field="([^"]+)"[^>]*>.*?</span>',
            replace_field, html_body, flags=re.DOTALL
        )
        html_body = re.sub(
            r'\{\{\s*(\w+)\s*\}\}',
            lambda m: ctx.get(m.group(1), m.group(0)),
            html_body
        )
        html_body = re.sub(
            r'<div[^>]+data-page-break[^>]*>.*?</div>',
            '<div style="page-break-after:always;"></div>',
            html_body, flags=re.DOTALL
        )
    else:
        rows = ''.join(
            f'<tr><td>{k.replace("_", " ").title()}</td><td>{v}</td></tr>'
            for k, v in ctx.items()
        )
        html_body = (
            f'<h1>Lease Agreement</h1>'
            f'<table border="1" cellpadding="6" style="border-collapse:collapse;width:100%">'
            f'{rows}</table>'
        )

    css = """
        @page { size: A4; margin: 2cm; }
        body { font-family: Arial, sans-serif; font-size: 10.5pt; line-height: 1.55; color: #111; }
        h1 { font-size: 14pt; font-weight: bold; text-align: center; margin-bottom: 12pt; }
        h2 { font-size: 11pt; font-weight: bold; margin: 8pt 0 3pt; }
        p, li { margin: 3pt 0; }
        table { border-collapse: collapse; width: 100%; margin: 4pt 0; }
        td, th { border: 1px solid #d1d5db; padding: 5pt 7pt; font-size: 10pt; }
        .filled { font-weight: 600; }
        .sig-page { page-break-before: always; }
        .sig-block { margin-bottom: 40pt; }
        .sig-line { border-bottom: 1px solid #333; width: 60%; margin-top: 36pt; }
        .sig-label { font-size: 9pt; color: #666; margin-top: 4pt; }
        .sig-date-line { border-bottom: 1px solid #333; width: 30%; margin-top: 36pt; display: inline-block; }
    """

    # Build a dedicated signature page so DocuSeal fields land on clean white space.
    sig_blocks = []
    tenant_name = ctx.get('tenant_name', 'Tenant')
    landlord_name = ctx.get('landlord_name', 'Landlord')
    parties = [
        ('LESSOR / LANDLORD', landlord_name),
        ('LESSEE / TENANT', tenant_name),
    ]
    co_tenants = ctx.get('co_tenants', '').strip()
    if co_tenants and co_tenants != '—':
        for i, name in enumerate(co_tenants.split(','), start=1):
            parties.append((f'CO-TENANT {i}', name.strip()))

    for role, name in parties:
        sig_blocks.append(
            f'<div class="sig-block">'
            f'<div class="sig-line"></div>'
            f'<div class="sig-label">{role}: {name}</div>'
            f'<div style="margin-top:8pt;">'
            f'<span class="sig-date-line"></span>'
            f'<span style="font-size:9pt;color:#666;margin-left:8pt;">Date</span>'
            f'</div>'
            f'</div>'
        )

    signature_page = (
        '<div class="sig-page">'
        '<h1 style="margin-bottom:24pt;">Signatures</h1>'
        '<p style="font-size:9.5pt;color:#444;margin-bottom:20pt;">'
        'By signing below, the parties confirm that they have read, understood, and agree '
        'to be bound by all the terms and conditions of this Lease Agreement.</p>'
        + ''.join(sig_blocks)
        + '</div>'
    )

    full_html = (
        '<!DOCTYPE html><html><head><meta charset="UTF-8">'
        f'<style>{css}</style></head><body>{html_body}{signature_page}</body></html>'
    )
    buf = io.BytesIO()
    result = pisa.CreatePDF(full_html, dest=buf)
    if result.err:
        raise RuntimeError("PDF generation failed")
    buf.seek(0)
    return buf.read()


def create_lease_submission(lease, signers: list, signing_mode: str = 'sequential') -> dict:
    """
    High-level function:
    1. Generate lease PDF
    2. Upload to DocuSeal as template
    3. Create submission with given signers (respecting signing_mode)

    signing_mode:
      - 'sequential' (default): signers go in order; each signer's 'order'
        field is sent to DocuSeal so the next signer is only invited once the
        previous one completes.  The order is determined by the position in the
        signers list unless an explicit 'order' key is provided.
      - 'parallel': everyone signs at once (no 'order' sent).

    Returns {'template': {...}, 'submission': [...]}
    """
    pdf_bytes = generate_lease_pdf(lease)
    tenant_name = lease.primary_tenant.full_name if lease.primary_tenant else 'Tenant'
    name = f"Lease - {tenant_name} - {lease.unit.property.name} Unit {lease.unit.unit_number}"

    template_data = upload_pdf_template(pdf_bytes, name, num_signers=len(signers))
    template_id = template_data['id']

    docuseal_roles = _roles_from_template(template_data)

    submitters = []
    for idx, s in enumerate(signers):
        if docuseal_roles and idx < len(docuseal_roles):
            role = docuseal_roles[idx]
        else:
            role = s.get('role') or 'First Party'
        entry = {
            'name': s['name'],
            'email': s['email'],
            'role': role,
            # Never let DocuSeal send emails — Tremly sends its own emails
            # with links to the custom Vue signing page (/sign/<uuid>/).
            'send_email': False,
        }
        if signing_mode == 'sequential':
            # Use explicit order if provided, otherwise position in the list
            entry['order'] = s.get('order', idx)
        submitters.append(entry)

    submission_data = create_submission(template_id, submitters)

    return {'template': template_data, 'submission': submission_data}
