# Generated by Django 5.2.12 on 2026-04-22 19:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0020_lease_deposit_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='First day of the rent period')),
                ('period_end', models.DateField(help_text='Last day of the rent period')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Expected rent for this period (ZAR)', max_digits=10)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit carried forward from previous cycle (ZAR). Positive = tenant in credit.', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('reversed', 'Reversed')], default='unpaid', max_length=15)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_invoices', to='leases.lease')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Bank reference or payment ID supplied by the tenant', max_length=150)),
                ('payer_name', models.CharField(blank=True, help_text='Name as it appeared on the bank statement', max_length=200)),
                ('source', models.CharField(choices=[('tenant', 'Tenant'), ('guarantor', 'Guarantor'), ('other', 'Other')], default='tenant', max_length=20)),
                ('status', models.CharField(choices=[('cleared', 'Cleared'), ('reversed', 'Reversed (Bounced EFT)')], default='cleared', max_length=15)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.rentinvoice')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnmatchedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('bank_statement_line', models.TextField(blank=True, help_text='Raw bank statement line for operator context')),
                ('status', models.CharField(choices=[('pending', 'Needs Reconciliation'), ('resolved', 'Resolved'), ('rejected', 'Rejected / Returned')], default='pending', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_sources', to='payments.rentinvoice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_unmatched_payments', to=settings.AUTH_USER_MODEL)),
                ('resolved_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_source', to='payments.rentpayment')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('invoice', 'Invoice'), ('payment', 'Payment'), ('unmatched', 'Unmatched Payment')], max_length=15)),
                ('entity_id', models.PositiveIntegerField(help_text='PK of the related entity')),
                ('lease_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.CharField(help_text="Short machine-readable event code, e.g. 'status_changed', 'payment_reversed'", max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Extra context: amounts, reasons, payer info, etc.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='payments_pa_entity__a1674e_idx'), models.Index(fields=['lease_id', '-created_at'], name='payments_pa_lease_i_225194_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['lease', 'status'], name='payments_re_lease_i_4eefc0_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['due_date'], name='payments_re_due_dat_ecefd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentinvoice',
            unique_together={('lease', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='unmatchedpayment',
            index=models.Index(fields=['status'], name='payments_un_status_ecb92a_idx'),
        ),
    ]
