# Generated by Django 5.2.12 on 2026-05-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_backfill_agency_id_accounts'),
        ('leases', '0025_backfill_agency_id_leases'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentauditlog',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Resolved from actor.agency or entity chain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_audit_logs', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Audit trail = legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Permanent (anonymise PI references).', max_length=32),
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from lease.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_invoices', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Rent invoice = SARS/FICA legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention. SARS/FICA 7-year floor for financial records.', max_length=32),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from invoice.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Rent payment = SARS/FICA legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention. SARS/FICA 7-year floor.', max_length=32),
        ),
        migrations.AddField(
            model_name='unmatchedpayment',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from assigned invoice on reconcile.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unmatched_payments', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='unmatchedpayment',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Bank deposit record = SARS/FICA legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='unmatchedpayment',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='fica_7yr', help_text='POPIA s14 retention. SARS/FICA 7-year floor.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['agency', '-created_at'], name='payaudit_agency_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['agency', 'status'], name='rentinv_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['agency', 'status'], name='rentpay_agency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unmatchedpayment',
            index=models.Index(fields=['agency', 'status'], name='unmatchpay_agency_stat_idx'),
        ),
    ]
