# Generated by Django 5.2.13 on 2026-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='legal_userc_user_id_81403f_idx',
            old_name='legal_userconsent_user_doc_idx',
        ),
    ]
