# Generated by Django 5.2.12 on 2026-05-06 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_popia_fields_user_person_etc'),
        ('legal', '0002_rename_legal_userconsent_user_doc_idx_legal_userc_user_id_81403f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Owning agency / tenant. Inherited from user.agency.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_consents', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='basis_evidence',
            field=models.TextField(blank=True, help_text='Form text / checkbox HTML at consent time (audit trail).'),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent (s11(1)(a))'), ('contract', 'Performance of contract (s11(1)(b))'), ('legal_obligation', 'Compliance with legal obligation (s11(1)(c))'), ('vital_interest', 'Protect vital interest (s11(1)(d))'), ('public_interest', 'Public interest / public function (s11(1)(e))'), ('legitimate_interest', 'Legitimate interest (s11(1)(f))'), ('operator_instruction', 'Processing on operator instruction (s21)')], default='legal_obligation', help_text='POPIA s11 basis. Consent record itself is a legal obligation.', max_length=32),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='retention_policy',
            field=models.CharField(choices=[('lease_lifetime', 'Lease lifetime + obligations cleared'), ('fica_5yr', 'FICA — 5 years from end of relationship'), ('fica_7yr', 'FICA / SARS — 7 years'), ('rha_3yr', 'RHA dispute records — 3 years'), ('audit_permanent', 'Audit trail — permanent (anonymise references)'), ('ai_chat_90d', 'AI chat / assistant — 90 days'), ('marketing_consent_lifetime', 'Marketing consent record'), ('none', 'No automated retention')], default='audit_permanent', help_text='POPIA s14 retention. Append-only; anonymise references after subject lifecycle.', max_length=32),
        ),
        migrations.AddField(
            model_name='userconsent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='POPIA s11(2) consent withdrawal timestamp.', null=True),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['agency', 'document', 'accepted_at'], name='uconsent_agency_doc_acc_idx'),
        ),
    ]
