# Generated by Django 5.2.12 on 2026-03-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_portal", "0003_tenantaiconversation_maintenance_report_suggested"),
        ("ai", "0002_migrate_legacy_tenant_chats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantaimessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='TenantAiConversation',
        ),
        migrations.DeleteModel(
            name='TenantAiMessage',
        ),
    ]
